### ISSUE TITLE
artifact name

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#10]
The published artifact for RC1 is `akka-management-cluster-http_2.11` but since the repo is named akka-cluster-management I think the correct name would be `akka-cluster-management-http_2.11`.

Also, the artifact name in the documentation is a third variant, i.e. wrong.

**Comment by 2m** [comment]
Artifact was named that way with the following naming scheme for future artifacts in mind:
```
akka-management-cluster-http  // already released from this repo
akka-management-cluster-jmx   // part of akka/akka, but could be moved here
akka-management-cluster-sharding-http // future management artifact for cluster-sharding
akka-management-stream-http   // future management artifact for stream
```

In light of this, repo name would be renamed to `akka-management`

**Comment by ktoso** [comment]
I agree with @2m, it seems sensible to have this as "akka-management"

PS: we changed the docs recently to reflect what was actually published too btw. 
https://github.com/akka/akka-cluster-management/commit/d1ac501a98a0c1c19c0c019b49d34089a2b3b7ef however we missed to release the 0.2 it seems, see https://github.com/akka/akka-cluster-management/issues/23

Let's decide naming before releasing 0.2 (close this issue, then release 0.2 to resolve https://github.com/akka/akka-cluster-management/issues/23 )

**Comment by patriknw** [comment]
ok, naming suggestion by @2m sounds good

**Comment by ktoso** [comment]
Renaming the repo too then 👍 
And will check artifact names.
