### ISSUE TITLE
Cluster Bootstrap fails with Unsupported Content-Type

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-management#108]
I have a very simple Akka Cluster demo, which I would like to bootstrap using Akka Management:
https://github.com/hseeberger/demo-akka-cluster

On 0.7 this worked, but on 0.9 I get the following errors:

```
13:49:57 ERROR HttpContactPointBootstrap [akka://dac@172.23.0.2:25520/system/headlessServiceDnsBootstrap/contactPointProbe-172.23.0.3-19999] -
Probing http://172.23.0.3:19999/bootstrap/seed-nodes failed due to Unsupported Content-Type, 
supported: application/json
```

**Comment by sebastianharko** [comment]
@hseeberger does the cluster HTTP management routes work though , so If you do curl -XGET http://172.23.0.3:19999/cluster/members ...do you get a response or do you still get the " failed due to Unsupported Content-Type, supported: application/json" message ?

**Comment by hseeberger** [comment]
That works. But of course the members are empty:

```
~/projekte/github/rocks.heikoseeberger/demo-akka-cluster(master ✔) http 172.20.10.3:32784/cluster-management/cluster/members
HTTP/1.1 200 OK
Content-Length: 72
Content-Type: application/json
Date: Thu, 18 Jan 2018 15:23:13 GMT
Server: akka-http/10.0.11

{
    "members": [],
    "selfNode": "akka://dac@172.23.0.3:25520",
    "unreachable": []
}
```

**Comment by ktoso** [comment]
Tagged, thanks.

Help very welcome in looking into this.

@sebastianharko @longshorej @hseeberger

**Comment by ktoso** [comment]
We need to set up integration tests -- any experience on that, with containers started from tests etc @longshorej or anyone else?

**Comment by sebastianharko** [comment]
@ktoso I can do integration tests , the CI server needs kubernetes etc.

**Comment by ktoso** [comment]
“the ci server” is just travis, so you can do everything in the travis file
:)
Thanks a lot!

-- 
Cheers,
Konrad 'ktoso <http://kto.so>' Malawski
Akka <http://akka.io/> @ Lightbend <http://lightbend.com/>

On January 19, 2018 at 0:23:43, Heiko Seeberger (notifications@github.com)
wrote:

That works. But of course the members are empty:

~/projekte/github/rocks.heikoseeberger/demo-akka-cluster(master ✔)
http 172.20.10.3:32784/cluster-management/cluster/members
HTTP/1.1 <http://172.20.10.3:32784/cluster-management/cluster/membersHTTP/1.1>
200 OK
Content-Length: 72
Content-Type: application/json
Date: Thu, 18 Jan 2018 15:23:13 GMT
Server: akka-http/10.0.11

{
    "members": [],
    "selfNode": "akka://dac@172.23.0.3:25520",
    "unreachable": []
}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-management/issues/108#issuecomment-358679831>,
or mute the thread

**Comment by sebastianharko** [comment]
@ktoso just submitted a PR to the Travis yaml file so that we can have minikube on the CI server

**Comment by longshorej** [comment]
I'll look into this today.

**Comment by longshorej** [comment]
Hrm - having a hard time reproducing @hseeberger, maybe I'm missing something obvious? Could you attach the K8s YAML you're using to deploy or add it to that repository? Maybe also ensure clean compile was done?

**Comment by hseeberger** [comment]
No K8s, Docker Compose. It's all in the repo.

**Comment by longshorej** [comment]
Ah - okay, thanks. Reproduced with `docker-compose up --scale dac=2`, I'll let you know what I find.

**Comment by hseeberger** [comment]
Thanks, mate!

**Comment by longshorej** [comment]
Ah, so the client has always ignored the `akka.management.http.base-path` setting for cluster bootstrap. In 0.7, the server ignored it too (https://github.com/akka/akka-management/blob/v0.7/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/contactpoint/HttpClusterBootstrapRoutes.scala#L39-L44). In 0.9, we're now respecting it but the client still isn't.

Workaround: remove base-path declaration

Fix: Make client respect the setting, I'll PR that, may still have some time today

**Comment by hseeberger** [comment]
Yay. Thanks for the findings!

**Comment by hseeberger** [comment]
Thanks!

**Comment by hseeberger** [comment]
@longshorej wait, do I really have to set `hostname` to `bind-hostname`? I'd prefer to be able to use `0.0.0.0` for `bind-hostname`.

**Comment by longshorej** [comment]
Sorry - I meant rename the key, i.e. set `bind-hostname` to `0.0.0.0`, not `hostname` (as was in the example)

**Comment by hseeberger** [comment]
Thanks. In docker I just use the default (the primary network address) for both.
