### ISSUE TITLE
Insufficient contact points discovered

### ISSUE THREAD

**Issue by jedossa** [akka/akka-management#114]
When I run `boostrap-joininig-demo-kubernetes-api`, I got not contact points (k8s `v1.8`): `[akka.tcp://Appka@172.17.0.5:2552/system/headlessServiceDnsBootstrap] Discovered [0] observation, which is less than the required [2], retrying (interval: 1.000 s)`.

**Comment by longshorej** [comment]
I'm not sure that example was ever finished. I'll look into this tomorrow and verify if it works / fix it if it doesn't.

Also relevant are the integration tests discussion that's currently WIP, but perhaps we should ensure all examples are tested nightly or something...
