### ISSUE TITLE
[Question] Scalac options and warnings

### ISSUE THREAD

**Issue by jedossa** [akka/akka-management#116]
I've seen warnings on compilation time about unused imports, params and/or functions. I'm working in a PR for addressing that. What warnings have you considered to add to `scalacOptions` ?

**Comment by ktoso** [comment]
We're on the default params and have not really considered much at this point for this project.
Feel free to remove unused imports though

**Comment by ktoso** [comment]
If anything, it can follow what we do in Akka https://github.com/akka/akka/blob/009214ae07708e8144a279e71d06c4a504907e31/project/AkkaBuild.scala
