### ISSUE TITLE
selfBaseUri broken

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-management#124]
AkkaManagement.scala, line 95:

``` scala
val selfBaseUri = Uri(s"$protocol://$hostname:$port/${settings.Http.BasePath}")
```

The problem is: `val BasePath: Option[String]` (in AkkaManagementSettings.scala)

**Comment by hseeberger** [comment]
OK, seems to be fixed in master. When do we get a new release?

**Comment by ktoso** [comment]
Use 0.10.0 :P

**Comment by hseeberger** [comment]
D'oh! `dependencyUpdates` didn't show me that there's a new release. Thanks!

**Comment by ktoso** [comment]
Hmm that's weird, it's out there http://search.maven.org/#search%7Cga%7C1%7Cakka-management
Cheers 👋
