### ISSUE TITLE
K8s API should honor deletionTimestamp

### ISSUE THREAD

**Issue by longshorej** [akka/akka-management#126]
When an operator requests that a pod be deleted, the K8s REST API includes a non-null value for `deletionTimestamp` in its metadata.

I think we should filter out any such pods from discovery such that we don't attempt to make contact with pods that are in the process of being terminated (i.e. K8s has sent them `SIGTERM` and it's waiting for them to exit)

**Comment by ktoso** [comment]
Great point! Are you planning to PR this?

**Comment by longshorej** [comment]
Yeah, hopefully I'll still have some time this week. I'm not sure about the Marathon situation but there's probably something similar there too.
