### ISSUE TITLE
Make "lowest address" pluggable

### ISSUE THREAD

**Issue by longshorej** [akka/akka-management#133]
*Wanted to get the discussion started on this. I think the only "bullet proof" way to do this is to have the scheduler coordinate termination with the application itself (we've discussed this before), but this feature would at least be an improvement over what we have now and seems like low hanging fruit.*

------------------------

I think the lowest address sort that is done now needs to be pluggable. The scheduler may have access to additional information that akka-management itself doesn't, e.g. which instance was started first (via timestamp metadata). As it is now, the hard-coded behavior of "lowest address" isn't consistent with that, and thus termination strategies such as youngest may not be as effective as they could be, causing singletons to bounce around more than they'd have to.

Alternatively,we could modify the contract of discovery so that it should return the nodes already sorted. Given K8s/Marathon APIs, they would have access to the required information already to do this sort. DNS impl could simply return them sorted by address. This may be conflating concepts a bit, not sure.

Thoughts?

**Comment by blublinsky** [comment]
Did you look at k8 stateful sets. They seem to provide all of the machinery and guarantees. Too bad DC/OS does not have the same thing

**Comment by longshorej** [comment]
Yes, there's a number of issues, the biggest for this particular problem being that use of `StatefulSet` precludes the use of readiness checks.

Even if this wasn't a problem, the deployment strategy for `StatefulSet` isn't ideal for Cluster Singleton. It terminates instances from `n` to `0`. This works nicely for the first rolling upgrade. Given a second rolling upgrade, this will bound the singleton from `n` to `n-1` .. `0` for each step. The third rolling upgrade will be fine, but the fourth will suffer the same problem as the second.

You can choose to terminate from `0` to `n` as well, this suffers from the same problem but is offset by one.

**Comment by ktoso** [comment]
@longshorej that's very interesting info, could you please open a top level ticket about "why not (yet) stateful sets"? People ask this question and my answer was a bit fuzzy "i heard something does not quite match", so being able to direct to such ticket would help a lot (services too).

**Comment by ktoso** [comment]
> As it is now, the hard-coded behavior of "lowest address" isn't consistent with that, and thus termination strategies such as youngest may not be as effective as they could be, causing singletons to bounce around more than they'd have to.

I think I see what you're getting at... that the external service does blindly terminate in the order "it thinks youngest -> oldest", but we joined "lowest" (youngest -- age, lowest -- address sorting). I thought we'd inform the cluster tools about what order to shut down things, but perhaps that's not doable and we should make sure to join in the order the cluster runner thinks "youngest" are offered hm.

Did I get that right?

In general making the decision pluggable sounds good anyway btw. Just trying to make sure we add it in the right spot etc

**Comment by longshorej** [comment]
> Did I get that right?
Yes, exactly. 

>  I thought we'd inform the cluster tools about what order to shut down things
That's the best way for sure. I think we can have both though -- pluggable address sorting would be pretty quick to implement and would improve things on DC/OS today. Long term, we need a better mechanism for rollouts/termination as you said.

> Perhaps this is a hairy topic enough to do a call about this or next week? I'm flying a lot tomorrow, but we could do it on friday?

Yeah, probably. I'll send an email out later today.

**Comment by sebastianharko** [comment]
>> we could modify the contract of discovery so that it should return the nodes already sorted

+1 for this, since it's easy and clear

**Comment by patriknw** [comment]
For removing (graceful rolling upgrades) I think we might need something else, such as asking the management api which nodes to remove. It has the better knowledge where e.g. cluster singleton lives. In the end it's not sure that the "oldest" is the same as the joining order (e.g. if many join at the "same" time).

That said, making the joining ordering pluggable can have its merits in itself.

**Comment by ktoso** [comment]
This will be solved by #144 as well, so closing

**Comment by ktoso** [comment]
(Yes, we're making it plugable)

**Comment by patriknw** [comment]
Solved by https://github.com/akka/akka-management/pull/154 by making the joining decision pluggable
