### ISSUE TITLE
K8s API fails if service account cannot view pod list

### ISSUE THREAD

**Issue by longshorej** [akka/akka-management#137]
Just logging this to note that it's a problem, and that I am working on a PR.

If using the K8s API for discovery, it will fail if the service account doesn't have access to list pods.

This is by design and there is no work around for this; your service account must have access to list pods within its namespace to use the K8s API.

Solving this issue therefore means

1) Sensible error messages
2) Documentation on how to configure your K8s cluster

**Comment by ktoso** [comment]
Great, thank you
