### ISSUE TITLE
Link into Tech Hub documentation index

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-management#139]
The Akka Management documentation is available at https://developer.lightbend.com/docs/akka-management/current/

However, it is not listed in the documentation index at https://developer.lightbend.com/docs/

**Comment by raboof** [comment]
Does it belong there? It is of course an open source component, but not really an 'open source project' in the sense of the other projects on that page. Perhaps we should put some example projects under https://developer.lightbend.com/start/?group=akka and add it under https://akka.io/docs/?

**Comment by ktoso** [comment]
> erhaps we should put some example projects under https://developer.lightbend.com/start/?group=akka and add it under https://akka.io/docs/?

Sounds good -- esp adding it into Akka docs listing, and even inside the docs themselfes to refer to it in deployment suggestions. Would you take a stab at it maybe?

**Comment by TimMoore** [comment]
It is listed at https://akka.io/docs/ now, so I'll close this.

However, I've made another related suggestion in #212.

**Comment by ktoso** [comment]
Assigned milestone for trackability
