### ISSUE TITLE
kubernetes-api discovery uses IPs instead of names

### ISSUE THREAD

**Issue by treyhyde** [akka/akka-management#142]
```
 private[kubernetes] def targets(podList: PodList, portName: String): Seq[ResolvedTarget] =
    for {
      item <- podList.items
      if item.metadata.deletionTimestamp.isEmpty
      container <- item.spec.containers
      port <- container.ports.find(_.name == portName)
      ip <- item.status.podIP
    } yield ResolvedTarget(ip, Some(port.containerPort))
```

Is it necessary to use the ip hear instead of the name?   This pretty much guarantees split brain when the service is restarted and the pods have new IPs.  I _think_ this is only invoked on startup and not every time members of the cluster need to find a new master (still trying to dig through the code).

Am I understanding this correctly?

Thanks

**Comment by treyhyde** [comment]
Somewhat related to #156, #134

**Comment by thomschke** [comment]
see #217

**Comment by chbatey** [comment]
Yes this is only used for bootstrap / new members joining.

If a pod comes back with a different IP the old instance will either have gracefully left the cluster or would need to be downed e.g. by SplitBrainResolver and pod the the new IP will be joining as a new node.
