### ISSUE TITLE
Make joining decision pluggable

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#144]
For cases where only using the lowest address of the discovered node is not desired.

The strategy should be given information from the discovery, and additional information that could be useful, e.g. for how long it has been probing and such.

This would probably also solve https://github.com/akka/akka-management/issues/133 (perhaps even a duplicate).

A decision can also be to continue probing.

**Comment by ktoso** [comment]
Yeah it's likely duplicate but let's keep both in the milestone as they have nice discussion
