### ISSUE TITLE
PodList parsing is too strict, needs higher-level error reporting

### ISSUE THREAD

**Issue by patrick-premont** [akka/akka-management#147]
The parsing of the response in `KubernetesApiSimpleServiceDiscovery.scala` is too strict. Also,  failures, which prevent cluster formation, are difficult to diagnose.

The newly added error message pointing to RBAC settings can be helpful, but I've seen other reasons for failure.

Changing the type of `PodList.Port.name` to `Option[String]` would eliminate one type of parse failure I've seen.

Another parse error could be caused (and I think I've seen that one too) by `PodList.Container.ports`, which should also be [optional](https://kubernetes-v1-4.github.io/docs/api-reference/v1/definitions/#_v1_container).

That might be all, but we should check that these are the only changes required to comply with the Kubernetes PodList schema.

If after this more lax parsing, our service discovery needs fields that were missing, it should ideally report which field it is missing, and from which pod.

An empty list of returned pods should likely issue a message like "No pods found with label ...".

**Comment by longshorej** [comment]
Thanks @patrick-premont.

Relevant code: https://github.com/akka/akka-management/blob/master/discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/PodList.scala

I reviewed the links API docs and cross-referenced with our definitions. Seems that it should be the following (and note that means any calling sites will have to be adjusted):

```scala
object PodList {
  case class Metadata(deletionTimestamp: Option[String])
  case class Port(name: Option[String], containerPort: Int) // better name: `ContainerPort`
  case class Container(name: String, ports: Option[Seq[Port]])
  case class Spec(containers: Seq[Container]) // better name: `PodSpec`
  case class Status(podIP: Option[String]) // better name: `PodStatus`
  case class Item(spec: Option[Spec], status: Option[Status], metadata: Option[Metadata]) // better name: `Pod`
}

case class PodList(items: Seq[Item])

```
