### ISSUE TITLE
Kubernetes example documentation out of sync with code

### ISSUE THREAD

**Issue by patrick-premont** [akka/akka-management#148]
The yaml included here https://developer.lightbend.com/docs/akka-management/current/bootstrap.html#examples is a bit out of sync with the example's code, and is missing the important `actorSystemName` label.

**Comment by ktoso** [comment]
Marked as bug; those mistakes can lead to people thinking bootstrap does not work.

Thanks! Could you submit a fix maybe?

**Comment by patrick-premont** [comment]
Looks like this is included automatically when the documentation is built through:
```
@@snip [akka-cluster.yml](../../../../bootstrap-joining-demo/kubernetes-api/kubernetes/akka-cluster.yml)
```

So I suppose `akka-cluster.yml` was incorrect when the documentation of `0.10.0` was built, and the next rebuild will fix it.

**Comment by ktoso** [comment]
Ok :)
