### ISSUE TITLE
Update Akka Cluster on k8s guide to show bootstrap

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#159]
This guide should be rewritten to use akka management: https://developer.lightbend.com/guides/akka-cluster-kubernetes-k8s-deploy/

Anything missing from bootstrap, should be implemented to make this work

**Comment by suyambuganesh** [comment]
Hi @ktoso , the given link above seems to be broken.

**Comment by ktoso** [comment]
Works for me?

**Comment by suyambuganesh** [comment]
I am sorry. The issue was with my company proxy.

**Comment by chbatey** [comment]
We removed that guide and I think we've improved the management docs/demos enough to not need to replace it
