### ISSUE TITLE
K8 API: Discovery error when using "sidecar" container

### ISSUE THREAD

**Issue by Emmenemoi** [akka/akka-management#164]
Got "Object is missing required member 'ports'" when trying to bootstrap akka cluster with member pod built with sidecar containers: by definition there's no ports on sidecar container (pulling only the WAR), only the tomcat container has ports defined.

Using Kube 1.8 and akka-management 0.10.0

Example: https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar

**Comment by ktoso** [comment]
Could you share more info, entire stacktrace, and how you run this?
Do you mean that your main app wants to use bootstrap, but there is a sidecar container, that has no ports so it blows up?

**Comment by Emmenemoi** [comment]
In your example (https://github.com/akka/akka-management/blob/master/bootstrap-joining-demo/kubernetes-api/kubernetes/akka-cluster.yml), simply add a dummy container with no port:

`
...
containers:
      - name: dummy-war
         image: resouer/sample:v1
      - name: appka
        image: ktoso/akka-management-bootstrap-joining-demo-kubernetes-api:1.3.3.7
        imagePullPolicy: Never
...
`

When deserializing the k8 API response the "ports" property is hardcoded without verification if it exists (https://github.com/akka/akka-management/blob/master/discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala line 36).

=> Got "Object is missing required member 'ports'" and then stops the bootstrap process.
As a consequence, if at least 1 container within the pods forming the Akka cluster has no port: impossible for any pod to bootstrap or join the cluster.

**Comment by longshorej** [comment]
I think this was fixed in https://github.com/akka/akka-management/pull/149 - the next release should hopefully resolve for you. `ports` is an `Option` now so it can deal with the case of it missing.
