### ISSUE TITLE
Better logging when discovery mechanism fails to load

### ISSUE THREAD

**Issue by lmlynik** [akka/akka-management#165]
Continuing https://github.com/akka/akka-management/issues/163, there should be better logging and errors for that scenario

**Comment by ktoso** [comment]
Łukasz, please when opening a new ticket like this make it self-explanatory so people don't have to do detective work what better logging and "that scenario" means. Could you copy the relevant information here? Help us help you :-)

**Comment by chbatey** [comment]
E.g. `Illegal `akka.discovery.method` value 'kubernetes-api' or incompatible class! The implementation class MUST extend akka.discovery.SimpleServiceDiscovery and take an ExtendedActorSystem as constructor argument.` is not very helpful

**Comment by teroxik** [comment]
Going to create a PR for this, as it misguided me as well, just a missing AWS_REGION variable for local testing in a docker container, but because of an update for couple of minor versions though that the plugin is wrongly configured.
