### ISSUE TITLE
Provide "hardcoded" discovery mechanism, mostly for dev time

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#166]
As silly as it sounds, it can be pretty useful in real deployments or testing.
It should be able to configure a range of hosts to return, i.e. `2.2.2.2 - 2.2.2.10` as well as CIDR notation which can be useful when someone knows that they deploy only into this subnet and mostly fill it with nodes anyway (not sure how typical, but I can see some people wanting this) `a.b.c.d/24` (likely wrong example, bear with me ;-)).

For bootstrap this can be useful for local development, or simply when people run their own thingies on small scale and know the nodes, and don't have any k8s or anything else available.

**Comment by patriknw** [comment]
How is this different from `seed-nodes` in config?

**Comment by ktoso** [comment]
I think the only difference is the ease of swapping between the two.

`java -Dakka.discovery=mocked` which would use the configuration from application.conf
or without that, which would use the discovery mechanism that application.conf has configured.

With seed nodes you'd have to either:
- do a -D...seed-nodes= (setting arrays is a pain in typesafe config via parameters, since you have to do the `-D...0 = ... -D...1 = ...` syntax if I remember correctly?
- do your own -DdevMode = ... which would be picked up in your app, and load some additional config -- this is essentially what we'd prepackage here.

**Comment by ktoso** [comment]
Note also that discovery is not only used for bootstrap, but can be used in general as a service locator -- so it would be the same "im working local now, use the mocked resolutions" mechanism to mock out IPs to other things or services.

**Comment by mbuccini** [comment]
Good idea, it'd be nice to have a mechanism to allow some local testing that doesn't involve changing completely the setup. 

BTW: I think this is somewhat related to https://github.com/akka/akka-management/issues/162, therefore I am going to close that one and keep it for documentation.

**Comment by ktoso** [comment]
> @markusthoemmes Apr 13 19:58
> Hi, trying to grok akka/akka-management#166 in terms of actionability. Not sure I'm following your train of thought there: What you essentially want is to be able to specify an alternate list of nodes (not seed-nodes) which can be "activated" via akka.discovery.method = mocked?

yeah that's basically it; This is about changing the discovery of the "contact points" how we call them, and from there on the other joining mechanisms would take over

**Comment by dhpiggott** [comment]
I just hacked something together out of necessity that does this in my downstream project. If anyone wants to pinch it, refine it, and then contribute it as their own, please feel free! (I'm not sure I would have time to do so myself anytime soon).

It consists of this:
https://github.com/dhpcs/liquidity/blob/ad946d39c8a941914ce0825ef35e48c2dbecaa37/server/src/main/scala/com/dhpcs/liquidity/server/HardcodedSimpleServiceDiscovery.scala

And this:
https://github.com/dhpcs/liquidity/blob/ad946d39c8a941914ce0825ef35e48c2dbecaa37/server/src/main/resources/reference.conf

I ended up hacking it together out of necessity so that I could switch the downstream project over to using the upstreamed ECS discovery mechanism. The commit message in which I did so includes an explanation of why and shows how I'm using it for cluster formation in component tests: https://github.com/dhpcs/liquidity/commit/ad946d39c8a941914ce0825ef35e48c2dbecaa37

**Comment by ktoso** [comment]
Thanks for sharing; to clarify, the above is still a bit away from comittable here, as the configuration should be more dynamic than one hardcoded list for all incoming queries. but it's a good start ;)

**Comment by dhpiggott** [comment]
I know ;) It was more that I was thinking the example would help clear up any uncertainty w.r.t the use-case for anyone else reading this issue.

**Comment by TimMoore** [comment]
I don't understand the range/CIDR requirement. Is the idea that it would explode that and return every possible address? Clients would then just deal with the fact that many of those addresses wouldn't respond?

I'm not convinced that this is that useful, and it could be dangerous (e.g., if one of those addresses has something completely different listening to it, you could join the wrong cluster).

Is a config map of the form `"service-name": "host:port"` sufficient?

**Comment by ktoso** [comment]
Right the CIDR requirement we can skip I think, in practice it would potentially cause some issues.
I think a config map would be fine -- though likely more like (pseudo grammar)

```
key = addr || [ addr, addr, addr, ... ]
addr =  [name:]? host [:port]?
```

I was thinking adding a name would be nice since we may want to for a given key return both "the http port and the https port and the akka remoting port", kind of like SRV records do.

**Comment by ktoso** [comment]
if we want to model it much after SRV then those look like that btw:

```

case class SRVRecord(override val name: String, override val ttl: Int,
                     priority: Int, weight: Int, port: Int, target: String) extends DnsResourceRecord(name, ttl, DnsRecordType.SRV.code, DnsRecordClass.IN.code) {
```

Though I think we're fine with just name, port, target (host)

**Comment by TimMoore** [comment]
Agree @ktoso it's good to be able to optionally specify a list of addresses, or a child map of endpoint names… although I think I would flip it around and put the port name outside the list of addresses like:

```
service-name = {
  http = [ "host1:8080", "host2:8080" ]
}
```

The extra SRV fields are probably not necessary, I agree.

I would also say:

- If the endpoint name isn't specified in config (e.g., `service-name = ["host1:8080","host2:8080"]` or just `service-name = "host:8080"`) then it should return that result for any endpoint name provided to the API (once #215 is implemented and the API supports endpoint names)
- Maybe (less sure about this) it should also support splitting a comma-separated string as an alternative to a HOCON list: `service-name = "host1:8080,host2:8080"`

  This would make it easier to substitute into `application.conf` from an environment variable:

  ```
  user-service = {?USER_SERVICE_LOCATIONS}
  ```
  then run: `USER_SERVICE_LOCATIONS="host1:8080,host2:8080" bin/start`
- Let's call it `ConfigSimpleServiceDiscovery` or something like that, and not imply too strongly that this is only for development. I think simple deployments when people are just starting out will want to use this for production, too.

**Comment by chbatey** [comment]
I added a config based service discovery in #218 I didn't add the simple version where we just split it but added an issue https://github.com/akka/akka-management/issues/219
