### ISSUE TITLE
Revisit log level in some components

### ISSUE THREAD

**Issue by markon** [akka/akka-management#174]
As of now, we are logging lots of statements with log-level "INFO". However, some logging should be set to DEBUG level, for example all the information coming from the bootstrap extensions, like here:

https://github.com/akka/akka-management/blob/1e774fe6be1aa410644ace486681881942df61fb/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala#L228

Related to comment: https://github.com/akka/akka-management/pull/172/files/dcf8fb3d35e9acc860a55e000cc447e551c646f0#r180649982

**Comment by ktoso** [comment]
Yeha good idea, please submit a PR with the ones you'd suggest being debug

**Comment by chbatey** [comment]
I switched this a while back as I thought it wasn't targeted at users
