### ISSUE TITLE
Aggregate service discovery

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#176]
Nowadays people can do AkkaDiscovery(). to get a "default one".
The default one is configured to a specific one.
It is useful to be able to configure by address range or prefix match, which lookup mechanism should be used for given input. Imagine a set of known hardcoded things, and a set of not known service located things which one has to go via DNS or other discovery -- this way, once configured, one does not have to change code once these change etc.

One can use hardcoded for locally being developed services, but keep the located ones for other cloud things etc and mix it depending how you need.

```
akka.discovery { 
  default = aggregate // or composite

  aggregate { 
    switch { 
      "*.example.com": akka-dns
      "google.com": gcloud-api 
     "*service": 127.0.0.1 // hardcode it for development time if you want (can be set via -D value on starting app etc)
      etc etc
```

**Comment by ignasi35** [comment]
This would be of great use for Lagom, for example. 

In current Lagom, configuring lookup for Kafka and Cassandra slightly differs. Both default to use Lagom's Service Locator but overriding each of the to use hardcoded [brokers lists](https://www.lagomframework.com/documentation/1.4.x/java/ProductionOverview.html#Using-static-Cassandra-contact-points) (Kafka) or [contact points](https://www.lagomframework.com/documentation/1.4.x/java/KafkaClient.html#Lagom-Kafka-Client1) (Cassandra) differs in both the format and the settings required.

**Comment by TimMoore** [comment]
You'll also need to be able to specify ports for hardcoded services.

Given that, I think something simpler than what's proposed above might be enough. Do we really need pattern matching on the names and multiple destinations?

I'd rather see an ordered sequence of lookup mechanisms, where anything not found in an earlier one is looked up in the next one.

The configuration mechanism could just be a straight map of `"name": "host:port"` pairs.

It could also be useful to pass even the results of successful lookups on to the next stage, so you could provide config like `"user-service": "_https._tcp.user-service.some-namespace.svc.cluster.local"` and then it will still get resolved by the DNS SRV mechanism.

**Comment by alanngai** [comment]
this is not a well formed thought, but I imagine at some point this may run up against alternative solutions to the same general problem of "selecting" different configurations for different environments.  In the case of kubernetes for example, the "canonical" solution is to use ConfigMap objects, which would be different for each environment, to house environment specific settings.  There is a request, for example, for reactive-lib to support ConfigMaps (https://github.com/lightbend/reactive-lib/issues/51).

I can see how it might confuse a developer how to use these different mechanisms in which context unless we first articulate what that strategy should be.  Perhaps a first step is to more clearly articulate the use cases, stakeholders, platforms, etc., and then determine what the right strategy should be

**Comment by TimMoore** [comment]
@alanngai that's a good point, but I think it's more general than this issue, because it could affect _any_ config, right?

**Comment by chbatey** [comment]
Planning on starting on this tomorrow so if you have any more ideas let me know @TimMoore

**Comment by TimMoore** [comment]
Thanks @chbatey.

I think the first step should be to implement a separate `ConfigSimpleServiceDiscovery` like what is discussed in #166. This is useful on its own.

Then, this composite one would use `ConfigSimpleServiceDiscovery`, `DnsSimpleServiceDiscovery`, and another implementation provided by users via config and chain them together:

Config → user → DNS

Alternatively, you could make it an arbitrary list of implementations loaded from config, but maybe that's more complex than necessary. Either is fine from my perspective.
