### ISSUE TITLE
aws-api discovery drops all ec2 filters but `otherFilters`

### ISSUE THREAD

**Issue by fabienrenaud** [akka/akka-management#177]
In [Ec2TagBasedSimpleServiceDiscovery](https://github.com/akka/akka-management/blob/master/discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala):

```java
    val tagKey = system.settings.config.getConfig("akka.discovery.aws-api-ec2-tag-based").getString("tag-key")
    val tagFilter = new Filter("tag:" + tagKey, List(name).asJava)

    val runningInstancesFilter = new Filter("instance-state-name", List("running").asJava)

    val otherFiltersString =
      system.settings.config.getConfig("akka.discovery.aws-api-ec2-tag-based").getString("filters")

    val otherFilters: util.List[Filter] = parseFiltersString(otherFiltersString).asJava

    val request = new DescribeInstancesRequest()
      .withFilters(runningInstancesFilter)
      .withFilters(tagFilter)
      .withFilters(otherFilters)
```

`runningInstancesFilter` is a Filter, tagFilter is a Filter, but otherFilter is a collection.
In [aws-java-sdk-ec2 v1.11.292](https://github.com/akka/akka-management/blob/master/project/Dependencies.scala#L85), `withFilters(Collection)` is a **set** operation. Only `withFilters(Filter...)` appends. From decompiled code:
```java
class DescribeInstancesRequest ... {

    public DescribeInstancesRequest withFilters(java.util.Collection<Filter> filters) {
        setFilters(filters);
        return this;
    }

    public void setFilters(java.util.Collection<Filter> filters) {
        if (filters == null) {
            this.filters = null;
            return;
        }

        this.filters = new com.amazonaws.internal.SdkInternalList<Filter>(filters);
    }

    public DescribeInstancesRequest withFilters(Filter... filters) {
        if (this.filters == null) {
            setFilters(new com.amazonaws.internal.SdkInternalList<Filter>(filters.length));
        }
        for (Filter ele : filters) {
            this.filters.add(ele);
        }
        return this;
    }
```

This causes the `runningInstancesFilter` and `tagFilter` filters to be dropped, which results in fetching and akka-discovery against ALL ec2 instances in the aws account (thousands in my case). The only workaround is to set a custom ec2 tag filter in the application configuration at this moment.

The 2 single filters + collection should be merged into a single list and `setFilters` should be used instead to avoid ambiguities.

The mysterious null IP address (see comment in the file) may have been caused by the `runningInstancesFilter` being dropped...

**Comment by ktoso** [comment]
Thanks for reporting and the fix! Will merge and release soon
