### ISSUE TITLE
AsyncEcsSimpleServiceDiscovery -- listTaskArns needs a cluster name

### ISSUE THREAD

**Issue by mikx** [akka/akka-management#180]
Otherwise, per AWS documentation, the default cluster is assumed, and if wrong, the discovery will fail.

**Comment by mikx** [comment]
The describeTasks function also needs cluster name, simply using task arn does not work....

**Comment by dhpiggott** [comment]
Ack, good point! The downstream project that the implementation came from was using the default cluster, hence not needing this. I've opened #182 to add support for overriding it.
