### ISSUE TITLE
Log an error or shut down if no nodes discovered during bootstrap.

### ISSUE THREAD

**Issue by longmuir** [akka/akka-management#183]
This was found using the kubernetes-api plugin. If no members are found during the initial startup (easy to occur with an error in configuration of either bootstrap or in K8s), the nodes will form as a cluster of 1. This appears to create a split brain type scenario with multiple clusters active, with similar consequences.

At the very least, there should be an error log if Cluster Bootstrap starts with no members found. Better yet, would be to stop the Actor System entirely as it's not likely we'd want to continue in this state, though I haven't thought through all of the consequences of this. I don't see attempting to restart the application or hoping for a better situation as desirable, as the orchestration tool (K8s) should handle that.

**Comment by chbatey** [comment]
I think the logging when self is not included is enough for now. We can re-open if we want to actually shut down.
