### ISSUE TITLE
Documentation: Kuberentes API Akka remoting port

### ISSUE THREAD

**Issue by longmuir** [akka/akka-management#184]
The sample configuration for the Kubernetes API uses the Akka remoting port 2551, which is not the default Akka remoting port (2552). This caused some needless time debugging. Using the default port here will be best for most.

https://developer.lightbend.com/docs/akka-management/current/discovery.html#discovery-method-kubernetes-api

**Comment by raboof** [comment]
Agreed! We use 2551 in examples sometimes if we want to run multiple actor systems on the same machine, but the default is 2552 so it is better to show that there.

**Comment by ktoso** [comment]
Thanks for solving @raboof, please close tickets and assign milestones when merging things.
