### ISSUE TITLE
Cluster bootstrap with DNS does not work when akka management host is a host rather than IP

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#187]
akka1 resolves to say IP 127.0.0.1

The self join check then compares akka1 with 127.0.0.1 at:

https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala#L138

Example config

```
akka {

  actor {
    provider = "cluster"
  }

  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "akka1"
      canonical.port = 25551
    }
  }

  discovery {
    method = akka-dns
  }

  management {
    http {
      port = 19999
      hostname = "akka1"
    }

    cluster.bootstrap {
      contact-point-discovery {
        service-name = "akka1"
        required-contact-point-nr = 1

      }
      contact-point {
        fallback-port = 19999
      }
    }
  }

}
```

**Comment by patrick-premont** [comment]
I've observed the same referenced comparison failing for a different reason. `akka.management.hostname` was not set, leading to `InetAddress.getLocalHost.getHostAddress` to be used instead, which somehow didn't match the host of the lowest IP returned by discovery, probably because it returned `127.0.0.1`.

Also, the log messages do not reflect what is actually compared, so they are unhelpful and appear contradictory:
```
15:37:39 INFO  HeadlessServiceDnsBootstrap [akka.tcp://x@10.52.2.10:10000/system/headlessServiceDnsBootstrap] - Contact point [http://10.52.2.10:10001] exceeded stable margin with no seed-nodes in sight. Considering whether this node is allowed to JOIN itself to initiate a new cluster.
15:37:39 INFO  HeadlessServiceDnsBootstrap [akka.tcp://x@10.52.2.10:10000/system/headlessServiceDnsBootstrap] - Exceeded stable margins without locating seed-nodes, however this node is NOT the lowest address out of the discovered IPs in this deployment, thus NOT joining self. Expecting node Some(ResolvedTarget(10.52.2.10,Some(10001))) (out of List(ResolvedTarget(10.52.2.10,Some(10001)), ResolvedTarget(10.52.2.18,Some(10001)))) to perform the self-join and initiate the cluster.
```

**Comment by patriknw** [comment]
What shall we do about it? Add a check that the http hostname is the same as the remoting hostname for the self node?

**Comment by ktoso** [comment]
which could be fine... but let's log a warning then?
Maybe also a log warning when we resolve a 127.0.0.1 which in many cases is not what one wants -- well except when testing locally on one node or something... but generally one warning log about 127.0.0.1 could be good anyway

**Comment by raboof** [comment]
Perhaps the check for misconfigurations we discussed in #189 might help give earlier/better feedback here as well?

**Comment by herzrasen** [comment]
@ktoso have there been any changes made to the master branch lately? Yesterday I experienced the same problems while bootstrapping on a Docker Swarm. Today I built the master branch locally to add some Logging and suddently the bootstrapping is working correctly.

**Comment by ktoso** [comment]
Well it is under active development... not sure what was "last time" for you.

**Comment by herzrasen** [comment]
Sorry, I was vague. The problem occurs when using the latest build (0.14.0).

**Comment by herzrasen** [comment]
It seems like setting akka.management.http.hostname to ${HOST} leads to a comparison between an IP address and a hostname when trying to figure out the lowest address of the contact points found.

**Comment by ktoso** [comment]
I see, thanks for finding that. I'll ponder it a bit soon

**Comment by markon** [comment]
I don't know if this is related, however I noticed that when you use "bind-hostname" it works. (at least it worked in my local kubernetes environment with kubernetes discovery, which should not be so different, though, because the decider is the same). 

I confirm that setting "hostname=localhost" won't work, as you mentioned.

**Comment by lustefaniak** [comment]
This happens all the time since 0.15 release which switched K8s IP lookup to be name based.

When upgrading to 0.15 I get now:
```Exceeded stable margins without locating seed-nodes, however this node is NOT the lowest address out of the discovered IPs in this deployment, thus NOT joining self. Expecting node [10-110-192-21.chronicle-s2.pod.cluster.local:Some(8558)] (out of [10-110-192-21.chronicle-s2.pod.cluster.local:Some(8558)]) to perform the self-join and initiate the cluster.```

**Comment by raboof** [comment]
@lustefaniak as this is an especially painful special case of this more general problem I created a separate ticket in #236

**Comment by eed3si9n** [comment]
I am also hitting the special-case pain (not being able to bootstrap on k8s) mentioned by @raboof, so I sent a PR addressing that part of the story - https://github.com/akka/akka-management/pull/242
