### ISSUE TITLE
Agressive usage of AWS EC2 API leads to rate limiting

### ISSUE THREAD

**Issue by StephenKing** [akka/akka-management#193]
It might be worth to reduce the aggressiveness of the API usage during (unsuccessful) bootstrapping:

> WARN  a.m.c.b.i.BootstrapCoordinator akka.tcp://esc@10.89.16.140:2541/system/bootstrapCoordinator   - Resolve attempt failed! Cause: com.amazonaws.services.ec2.model.AmazonEC2Exception: Request limit exceeded. (Service: AmazonEC2; Status Code: 503; Error Code: RequestLimitExceeded; Request ID: cca286ee-7ff4-4e9b-8dc0-8350904c11b2)

**Comment by ktoso** [comment]
Thanks for reporting; you're right;
Do you think you could help out on this one by providing a pull request?

**Comment by StephenKing** [comment]
Thanks for looking at this @ktoso. I don't know much scala unfortunately, but I would give my best.

Question is.. how to improve it.

Options that I see:

- `akka.management.cluster.bootstrap.contact-point-discovery.interval = 1 second` could be increased in general (one probably doesn't want to hit K8s APIs heavily as well..)
- exponential backoff (with some upper bound of maybe 10s

Regarding the exponential backoff, I read that the AWS SDK automatically retries backoff when rate limits are exceeded. I guess, we ignore that and schedule yet another API request? If that would be the case (I don't have the env running right now), then `setRetryPolicy(PredefinedRetryPolicies.NO_RETRY_POLICY)` could already reduce aggressiveness.

Or aren't we kicking off another run for the service discovery if the previous didn't finish, yet?

**Comment by ktoso** [comment]
Reopening as we want to add the backoff as well to consider this solved.

cc @raboof

**Comment by ktoso** [comment]
Thanks for the reports. backoff implemented as well!
