### ISSUE TITLE
required-contant-point-nr path incorrect in documentation

### ISSUE THREAD

**Issue by herzrasen** [akka/akka-management#210]
Hi,

in the docs it says:

> At least `akka.management.cluster.bootstrap.required-contact-point-nr` nodes have been discovered.

While in reference.conf the path to required-contact-point-nr is `akka.management.cluster.bootstrap.contact-point-discovery.required-contact-point-nr`

I could provide a PR if it helps.

**Comment by ktoso** [comment]
thanks a lot, yes please send in a PR :)
