### ISSUE TITLE
Error while importing sbt project:

### ISSUE THREAD

**Issue by liaolunhui** [akka/akka-management#213]
Error while importing sbt project:

Getting org.scala-sbt sbt 0.13.16  (this may take some time)...

:: problems summary ::
:::: WARNINGS
[FAILED     ] org.scala-sbt#sbt;0.13.16!sbt.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/sbt/0.13.16/sbt-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/sbt/0.13.16/jars/sbt.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/sbt/0.13.16/sbt-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/sbt/0.13.16/sbt-0.13.16.jar

[FAILED     ] org.scala-sbt#main;0.13.16!main.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/main/0.13.16/main-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/main/0.13.16/jars/main.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/main/0.13.16/main-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/main/0.13.16/main-0.13.16.jar

[FAILED     ] org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/compiler-interface/0.13.16/compiler-interface-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/compiler-interface/0.13.16/jars/compiler-interface.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/compiler-interface/0.13.16/compiler-interface-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/compiler-interface/0.13.16/compiler-interface-0.13.16.jar

[FAILED     ] org.scala-sbt#actions;0.13.16!actions.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/actions/0.13.16/actions-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/actions/0.13.16/jars/actions.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/actions/0.13.16/actions-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/actions/0.13.16/actions-0.13.16.jar

[FAILED     ] org.scala-sbt#main-settings;0.13.16!main-settings.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/main-settings/0.13.16/main-settings-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/main-settings/0.13.16/jars/main-settings.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/main-settings/0.13.16/main-settings-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/main-settings/0.13.16/main-settings-0.13.16.jar

[FAILED     ] org.scala-sbt#interface;0.13.16!interface.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/interface/0.13.16/interface-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/interface/0.13.16/jars/interface.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/interface/0.13.16/interface-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/interface/0.13.16/interface-0.13.16.jar

[FAILED     ] org.scala-sbt#io;0.13.16!io.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/io/0.13.16/io-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/io/0.13.16/jars/io.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/io/0.13.16/io-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/io/0.13.16/io-0.13.16.jar

[FAILED     ] org.scala-sbt#ivy;0.13.16!ivy.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/ivy/0.13.16/ivy-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/ivy/0.13.16/jars/ivy.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/ivy/0.13.16/ivy-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/ivy/0.13.16/ivy-0.13.16.jar

[FAILED     ] org.scala-sbt#logging;0.13.16!logging.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/logging/0.13.16/logging-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/logging/0.13.16/jars/logging.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/logging/0.13.16/logging-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/logging/0.13.16/logging-0.13.16.jar

[FAILED     ] org.scala-sbt#logic;0.13.16!logic.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/logic/0.13.16/logic-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/logic/0.13.16/jars/logic.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/logic/0.13.16/logic-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/logic/0.13.16/logic-0.13.16.jar

[FAILED     ] org.scala-sbt#process;0.13.16!process.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/process/0.13.16/process-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/process/0.13.16/jars/process.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/process/0.13.16/process-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/process/0.13.16/process-0.13.16.jar

[FAILED     ] org.scala-sbt#run;0.13.16!run.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content
/groups/public/org/scala-sbt/run/0.13.16/run-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/run/0.13.16/jars/run.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/run/0.13.16/run-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/run/0.13.16/run-0.13.16.jar

[FAILED     ] org.scala-sbt#command;0.13.16!command.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/command/0.13.16/command-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/command/0.13.16/jars/command.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/command/0.13.16/command-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/command/0.13.16/command-0.13.16.jar

[FAILED     ] org.scala-sbt#classpath;0.13.16!classpath.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/classpath/0.13.16/classpath-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/classpath/0.13.16/jars/classpath.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/classpath/0.13.16/classpath-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/classpath/0.13.16/classpath-0.13.16.jar

[FAILED     ] org.scala-sbt#completion;0.13.16!completion.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/completion/0.13.16/completion-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/completion/0.13.16/jars/completion.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/completion/0.13.16/completion-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/completion/0.13.16/completion-0.13.16.jar

[FAILED     ] org.scala-sbt#api;0.13.16!api.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/api/0.13.16/api-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/api/0.13.16/jars/api.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/api/0.13.16/api-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/api/0.13.16/api-0.13.16.jar

[FAILED     ] org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/compiler-integration/0.13.16/compiler-integration-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/compiler-integration/0.13.16/jars/compiler-integration.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/compiler-integration/0.13.16/compiler-integration-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/compiler-integration/0.13.16/compiler-integration-0.13.16.jar

[FAILED     ] org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/compiler-ivy-integration/0.13.16/jars/compiler-ivy-integration.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/compiler-ivy-integration/0.13.16/compiler-ivy-integration-0.13.16.jar

[FAILED     ] org.scala-sbt#relation;0.13.16!relation.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/relation/0.13.16/relation-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/relation/0.13.16/jars/relation.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/relation/0.13.16/relation-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/relation/0.13.16/relation-0.13.16.jar

[FAILED     ] org.scala-sbt#task-system;0.13.16!task-system.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/task-system/0.13.16/jars/task-system.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/task-system/0.13.16/task-system-0.13.16.jar

[FAILED     ] org.scala-sbt#tasks;0.13.16!tasks.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/tasks/0.13.16/tasks-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/tasks/0.13.16/jars/tasks.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/tasks/0.13.16/tasks-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/tasks/0.13.16/tasks-0.13.16.jar

[FAILED     ] org.scala-sbt#tracking;0.13.16!tracking.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/tracking/0.13.16/tracking-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/tracking/0.13.16/jars/tracking.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/tracking/0.13.16/tracking-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/tracking/0.13.16/tracking
-0.13.16.jar

[FAILED     ] org.scala-sbt#testing;0.13.16!testing.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/testing/0.13.16/testing-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/testing/0.13.16/jars/testing.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/testing/0.13.16/testing-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/testing/0.13.16/testing-0.13.16.jar

[FAILED     ] org.scala-sbt#control;0.13.16!control.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/control/0.13.16/control-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/control/0.13.16/jars/control.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/control/0.13.16/control-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/control/0.13.16/control-0.13.16.jar

[FAILED     ] org.scala-sbt#collections;0.13.16!collections.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/collections/0.13.16/collections-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/collections/0.13.16/jars/collections.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/collections/0.13.16/collections-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/collections/0.13.16/collections-0.13.16.jar

[FAILED     ] org.scala-sbt#classfile;0.13.16!classfile.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/classfile/0.13.16/classfile-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/classfile/0.13.16/jars/classfile.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/classfile/0.13.16/classfile-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/classfile/0.13.16/classfile-0.13.16.jar

[FAILED     ] org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/incremental-compiler/0.13.16/incremental-compiler-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/incremental-compiler/0.13.16/jars/incremental-compiler.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/incremental-compiler/0.13.16/incremental-compiler-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/incremental-compiler/0.13.16/incremental-compiler-0.13.16.jar

[FAILED     ] org.scala-sbt#compile;0.13.16!compile.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/compile/0.13.16/compile-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/compile/0.13.16/jars/compile.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/compile/0.13.16/compile-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/compile/0.13.16/compile-0.13.16.jar

[FAILED     ] org.scala-sbt#persist;0.13.16!persist.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/persist/0.13.16/persist-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/persist/0.13.16/jars/persist.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/persist/0.13.16/persist-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/persist/0.13.16/persist-0.13.16.jar

[FAILED     ] org.scala-sbt#cross;0.13.16!cross.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/cross/0.13.16/cross-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/cross/0.13.16/jars/cross.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/cross/0.13.16/cross-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/cross/0.13.16/cross-0.13.16.jar

[FAILED     ] org.scala-sbt#cache;0.13.16!cache.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/cache/0.13.16/cache-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/cache/0.13.16/jars/cache.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/cache/0.13.16/cache-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/cache/0.13.16/cache-0.13.16.jar

[FAILED     ] org.scala-sbt#test-agent;0.13.16!test-agent.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/test-agent/0.13.16/test-agent-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/test-agent/0.13.16/jars/test-agent.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/test-agent/0.13.16/test-agent-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/test-agent/0.13.16/test-agent-0.13.16.jar

[FAILED     ] org.scala-sbt#apply-macro;0.13.16!apply-macro.jar:  (0ms)

==== public: tried

http://maven.aliyun.com/nexus/content/groups/public/org/scala-sbt/apply-macro/0.13.16/apply-macro-0.13.16.jar

==== typesafe: tried

http://dl.bintray.com/typesafe/ivy-releases/bootOnly#这个ivy

==== ivy-sbt-plugin: tried

http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-sbt/apply-macro/0.13.16/jars/apply-macro.jar#这个ivy

==== Sonatype Releases Repository: tried

https://oss.sonatype.org/content/repositories/releases/org/scala-sbt/apply-macro/0.13.16/apply-macro-0.13.16.jar

==== Sonatype Snapshots Repository: tried

https://oss.sonatype.org/content/repositories/snapshots/org/scala-sbt/apply-macro/0.13.16/apply-macro-0.13.16.jar

::::::::::::::::::::::::::::::::::::::::::::::

::              FAILED DOWNLOADS            ::

:: ^ see resolution messages for details  ^ ::

::::::::::::::::::::::::::::::::::::::::::::::

:: org.scala-sbt#sbt;0.13.16!sbt.jar

:: org.scala-sbt#main;0.13.16!main.jar

:: org.scala-sbt#actions;0.13.16!actions.jar

:: org.scala-sbt#classpath;0.13.16!classpath.jar

:: org.scala-sbt#interface;0.13.16!interface.jar

:: org.scala-sbt#io;0.13.16!io.jar

:: org.scala-sbt#control;0.13.16!control.jar

:: org.scala-sbt#completion;0.13.16!completion.jar

:: org.scala-sbt#collections;0.13.16!collections.jar

:: org.scala-sbt#api;0.13.16!api.jar

:: org.scala-sbt#classfile;0.13.16!classfile.jar

:: org.scala-sbt#logging;0.13.16!logging.jar

:: org.scala-sbt#process;0.13.16!process.jar

:: org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar

:: org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar

:: org.scala-sbt#relation;0.13.16!relation.jar

:: org.scala-sbt#compile;0.13.16!compile.jar

:: org.scala-sbt#persist;0.13.16!persist.jar

:: org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar

:: org.scala-sbt#ivy;0.13.16!ivy.jar

:: org.scala-sbt#cross;0.13.16!cross.jar

:: org.scala-sbt#run;0.13.16!run.jar

:: org.scala-sbt#task-system;0.13.16!task-system.jar

:: org.scala-sbt#tasks;0.13.16!tasks.jar

:: org.scala-sbt#tracking;0.13.16!tracking.jar

:: org.scala-sbt#cache;0.13.16!cache.jar

:: org.scala-sbt#testing;0.13.16!testing.jar

:: org.scala-sbt#test-agent;0.13.16!test-agent.jar

:: org.scala-sbt#main-settings;0.13.16!main-settings.jar

:: org.scala-sbt#apply-macro;0.13.16!apply-macro.jar

:: org.scala-sbt#command;0.13.16!command.jar

:: org.scala-sbt#logic;0.13.16!logic.jar

:: org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar

::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Error during sbt execution: Error retrieving required libraries
download failed: org.scala-sbt#sbt;0.13.16!sbt.jar
download failed: org.scala-sbt#main;0.13.16!main.jar
download failed: org.scala-sbt#actions;0.13.16!actions.jar
download failed: org.scala-sbt#classpath;0.13.16!classpath.jar
download failed: org.scala-sbt#interface;0.13.16!interface.jar
download failed: org.scala-sbt#io;0.13.16!io.jar
download failed: org.scala-sbt#control;0.13.16!control.jar
download failed: org.scala-sbt#completion;0.13.16!completion.jar
download failed: org.scala-sbt#collections;0.13.16!collections.jar
download failed: org.scala-sbt#api;0.13.16!api.jar
download failed: org.scala-sbt#classfile;0.13.16!classfile.jar
download failed: org.scala-sbt#logging;0.13.16!logging.jar
download failed: org.scala-sbt#process;0.13.16!process.jar
download failed: org.scala-sbt#compiler-integration;0.13.16!compiler-integration.jar
download failed: org.scala-sbt#incremental-compiler;0.13.16!incremental-compiler.jar
download failed: org.scala-sbt#relation;0.13.16!relation.jar
download failed: org.scala-sbt#compile;0.13.16!compile.jar
download failed: org.scala-sbt#persist;0.13.16!persist.jar
download failed: org.scala-sbt#compiler-ivy-integration;0.13.16!compiler-ivy-integration.jar
download failed: org.scala-sbt#ivy;0.13.16!ivy.jar
download failed: org.scala-sbt#cross;0.13.16!cross.jar
download failed: org.scala-sbt#run;0.13.16!run.jar
download failed: org.scala-sbt#task-system;0.13.16!task-system.jar
download failed: org.scala-sbt#tasks;0.13.16!tasks.jar
download failed: org.scala-sbt#tracking;0.13.16!tracking.jar
download failed: org.scala-sbt#cache;0.13.16!cache.jar
download failed: org.scala-sbt#testing;0.13.16!testing.jar
download failed: org.scala-sbt#test-agent;0.13.16!test-agent.jar
download failed: org.scala-sbt#main-settings;0.13.16!main-settings.jar
download failed: org.scala-sbt#apply-macro;0.13.16!apply-macro.jar
download failed: org.scala-sbt#command;0.13.16!command.jar
download failed: org.scala-sbt#logic;0.13.16!logic.jar
download failed: org.scala-sbt#compiler-interface;0.13.16!compiler-interface.jar
(see C:\Users\liaolunhui\.sbt\boot\update.log for complete log)
Error: Could not retrieve sbt 0.13.16

**Comment by ktoso** [comment]
Are you sure you are not behind some corporate firewall?
