### ISSUE TITLE
Service discovery API for named ports/protocols

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-management#215]
Many service discovery implementations have some mechanism for distinguishing between multiple endpoints of a single service (for example, a service might listen to ports for http, akka-management-http, and akka-remote).

The details of how this works vary:

- [DNS SRV](https://www.ietf.org/rfc/rfc2782.txt) uses lookups of the form `_<service>._<protocol>.<name>`
- In [Kubernetes](https://github.com/kubernetes/dns/blob/master/docs/specification.md#232---srv-records), this translates to the form `_<port>._<proto>.<service>.<ns>.svc.<zone>.`, where each service defines a list of [port names and protocols](https://kubernetes.io/docs/concepts/services-networking/service/#multi-port-services)
- [Marathon](https://mesosphere.github.io/marathon/docs/networking.html#specifying-ports) works similarly to Kubernetes
- In [Consul's DNS SRV interface](https://www.consul.io/docs/agent/dns.html#rfc-2782-lookup), the service name is the first component, and the `<protocol>` component is translated to a Consul tag lookup.
- Consul's HTTP interface also support [filtering queries by tag](https://www.consul.io/api/catalog.html#tag)
- Most others have some similar kind of metadata/tagging facility

The Akka `SimpleServiceDiscovery` API should allow some way to optionally specify this additional port name and protocol along with the name. Then, individual implementation can decide the best way to use that information to query the back end.

**Comment by TimMoore** [comment]
The type of case we need to handle is when we want to build something on top of the service discovery API that should be independent of the underlying implementation. So for example in Lagom, if you make a request to a service named "user-service" (where the name is defined in the service API descriptor) then it looks up "user-service" in the service locator.

But then, service locator might be listening on several different ports: one for the main http server, one for akka-management-http, one for akka-remote, and now maybe a separate grpc port (still TBD whether we can have that share the same port as the main http server in early iterations without needing a lot more work).

So we need to translate "user-service" to some SRV name inside the DNS service discovery implementation, but how do we know which prefix to use?

Right now, Lightbend Orchestration hardcodes "_http", which it is also hardcoded to generate as a port name for Lagom services when creating the Kubernetes service definition YAML.

Not only is this too inflexible to handle a separate grpc port, but it also doesn't work correctly right now for Kafka and Cassandra, which require manual configuration.

So, we need some way for this to be passed through from user code. For Lagom's automatic lookups, we could add a config setting defaulting to "http" for service-to-service (compatible with existing) and something else for Kafka and Cassandra.

One option would be to pass it as part of the service name string. For example, we could adopt the Kubernetes convention of `_<port>._<protocol>.<service-name>`, then have other service discovery implementations parse that string and do whatever they need to do, but I think it's cleaner and more explicit to add more (optional) parameters to the API.

Even within the SRV implementation, different platforms have different conventions, so the translation pattern needs to be configurable. Consul uses names like `_<service-name>._<tag>.service.consul`. The name for `user-service` in Kubernetes might map to `_http._tcp.user-service.default.svc.cluster.local` while in Consul it maps to `_user-service._http.service.consul`.

**Comment by chbatey** [comment]
@TimMoore any thoughts about the specific API? Each mechanism calls things differently. Should we just take in a Map?

**Comment by chbatey** [comment]
Or should we be opinionated about it and take in an optional port and protocol?

**Comment by chbatey** [comment]
I'll go with optional arguments for service, port and protocol along with name being required. That way users pass in just a name it'll work as is. 

Then for SRV look ups if a user passed in just a name we can pass the whole thing to DNS but if they pass in the other bits we construct a _<service>._<protocol>.<name> etc
