### ISSUE TITLE
Problem with fetching akka-discovery-config and akka-discovery-aggregate

### ISSUE THREAD

**Issue by sebarys** [akka/akka-management#226]
Hi,

I am having troubles with fetching in my project following dependencies:
- `akka-discovery-aggregate`
- `akka-discovery-config`

In docs current version is `0.15.0+20180702-0732`, also I was looking for other versions but could not find anything.

```
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.lightbend.akka.discovery#akka-discovery-aggregate_2.12;0.15.0+20180702-0732: not found
[error] unresolved dependency: com.lightbend.akka.discovery#akka-discovery-config_2.12;0.15.0+20180702-0732: not found
[error] (*:update) sbt.ResolveException: unresolved dependency: com.lightbend.akka.discovery#akka-discovery-aggregate_2.12;0.15.0+20180702-0732: not found
[error] unresolved dependency: com.lightbend.akka.discovery#akka-discovery-config_2.12;0.15.0+20180702-0732: not found
```

Do I need to add any custom resolvers in my build.sbt to fetch that dependencies? There is no problem with getting `akka-management-cluster-bootstrap` and `akka-discovery-dns`.

Thanks for any suggestions and help ;)

**Comment by ktoso** [comment]
Sorry about that, it seems a version not directly from the tag of the docs was published so the automatic versioning plugin kicked in.

Please depend only on stable versions: `0.15.0`, thanks.
You can treat the docs as valid though

**Comment by ktoso** [comment]
We'll resolve this during 0.16 release very soon

**Comment by sebarys** [comment]
It looks that these artefacts are not available in `0.15.0` version - I am receiving the same message like for `0.15.0+20180702-0732`.

**Comment by ktoso** [comment]
They are available. See: https://search.maven.org/#search%7Cga%7C1%7Cakka-management
Please use 0.15.0

**Comment by sebarys** [comment]
I am having trouble with `akka-discovery` (`akka-discovery-aggregate` and `akka-discovery-config`) artefacts: https://search.maven.org/#search%7Cga%7C1%7Cakka-discovery

**Comment by TimMoore** [comment]
Looks like `akka-discovery-aggregate` and `akka-discovery-config` aren't aggregated in the root sbt project, so the release process must have skipped them.

https://github.com/akka/akka-management/blob/fd5c9b3d314a385b0724023e1f49d068f03eae09/build.sbt#L9-L23

**Comment by ktoso** [comment]
Good point about `akka-discovery-config`! Thanks.
Though the aggregate should not be published so that's fine.

**Comment by TimMoore** [comment]
Why not publish the aggregate one? (Possible confusion: two different meanings for the word "aggregate". In this context, it is the service discovery implementation that aggregates multiple other implementations.)

**Comment by ktoso** [comment]
lol, yeah, sorry I had thought we mean the root project was called that.
Yeah the "aggregate one" we want to publish... Fixing both now

**Comment by TimMoore** [comment]
I noticed a number of other projects that are also missing from the root project aggregate (other meaning of the word 😝)… mostly demos.

**Comment by ktoso** [comment]
Thanks for reporting @sebarys  and additional spotting @TimMoore !
We'll soon release 0.16 so that'll be there
