### ISSUE TITLE
K8s discovery example doesn't work with minikube v0.28.0 (k8s v1.10.0)

### ISSUE THREAD

**Issue by raboof** [akka/akka-management#235]
Perhaps related to #138 ?
```
[INFO] [07/10/2018 10:52:01.506] [Appka-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(Appka)] Querying for pods with label selector: [actorSystemName=appka]
[ERROR] [07/10/2018 10:52:01.516] [Appka-akka.actor.default-dispatcher-18] [akka.actor.ActorSystemImpl(Appka)] Failed to unmarshal Kubernetes API response status [403 Forbidden]; check RBAC settings
[WARN] [07/10/2018 10:52:01.523] [Appka-akka.actor.default-dispatcher-18] [akka.tcp://Appka@172.17.0.6:2552/system/bootstrapCoordinator] Resolve attempt failed! Cause: spray.json.DeserializationException: Object is missing required member 'items'
```

**Comment by TimMoore** [comment]
Minikube started enabling RBAC in new clusters by default from v0.26.0 (released 11 April, after this example was originally written). Things move quickly in kubeworld!

**Comment by aartek** [comment]
Could anyone confirm that the example works on minikube v0.28.0 (k8s v1.10.0).  I'm trying to run my application with manifests based on this [example](https://developer.lightbend.com/docs/akka-management/current/bootstrap.html) and I also get `Failed to unmarshal Kubernetes API response status [403 Forbidden]; check RBAC settings` error.

**Comment by raboof** [comment]
@aartek could you try adding the RBAC settings proposed in https://github.com/akka/akka-management/pull/237/files and report back if that resolves the issue for you? If so then we can merge that PR :smile:

**Comment by aartek** [comment]
@raboof I have the above settings in my manifest and it doesn't work for me

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
```
![image](https://user-images.githubusercontent.com/5053151/44203440-30eb1080-a14f-11e8-8e12-bfc88eeef529.png)

Do I need to start the minikube with any additional flag? Or simply `minikube start` should be enough?

**Comment by aartek** [comment]
I've found the reason why my app got this 403 error. I didn't specify the `K8S_NAMESPACE` env in my deployment 

```
env:
- name: K8S_NAMESPACE
   value: "default"
```

Now I can confirm that it works on minikube v0.28.0 (k8s v1.10.0)

**Comment by raboof** [comment]
:+1:
