### ISSUE TITLE
Would the `shutdown-after-unsuccessful-join-seed-nodes` setting even work?

### ISSUE THREAD

**Issue by ygree** [akka/akka-management#248]
I can't find any reference to the`shutdown-after-unsuccessful-join-seed-nodes` setting in the source code. There is only one reference in the documentation: https://github.com/akka/akka-management/blob/master/docs/src/main/paradox/bootstrap.md#recommended-configuration

```
15:18 $ git grep "shutdown-after"
docs/src/main/paradox/bootstrap.md:akka.cluster.shutdown-after-unsuccessful-join-seed-nodes = 40s
✔
```

May be a bug.

**Comment by thjaeckle** [comment]
Hi.
That is an Akka config key, not an akka-management one, see: https://github.com/akka/akka/blob/master/akka-cluster/src/main/resources/reference.conf#L36

**Comment by ktoso** [comment]
Yep, it’s as @thjaeckle explains. It’s a akka setting. You can tell by where it stands in the settings hierarchy. There is no “management” word in it, so it is not defined here
