### ISSUE TITLE
Extend PR validation to cover Akka cluster formation

### ISSUE THREAD

**Issue by dwijnand** [akka/akka-management#256]

**Comment by ktoso** [comment]
Let me know however I can help out here!

**Comment by chbatey** [comment]
We could add tests for `config` service discovery mechanism now. Were you also thinking in minikube?

**Comment by dwijnand** [comment]
I guess you're asking @ktoso: I created this issue from his comment https://github.com/lightbend/orchestration-team/issues/77#issuecomment-409785094.

**Comment by raboof** [comment]
I think both would be worthwhile, perhaps split the issue?

**Comment by ktoso** [comment]
As the bootstrap dance is kind of important for us it would be really good to have it in validation. 
Splitting into separate things sounds okey
