### ISSUE TITLE
Warning during DNS Bootstrapping

### ISSUE THREAD

**Issue by herzrasen** [akka/akka-management#257]
I'm getting a warning when trying to bootstrap using docker swarm based DNS. 

`2018-08-03 12:29:12.989 [WARN ] akka.io.dns.internal.AsyncDnsManager - Received Dns.Resolve(10.0.1.20) message while Async DNS resolver active. Please use the new API [akka.io.dns.DnsProtocol] to issue resolve requests. (This warning will be logged at most 10 times)`

In my application.conf is enabled
```
akka {
  discovery {
    method = akka-dns
  }

  io.dns.resolver = async-dns
}
```
Anything I can do to avoid this?

**Comment by eshepelyuk** [comment]
@herzrasen are you doing anything spefic for DNS discovery in swarm ? I can't make my cluster to bootstrap with swarm DNS, althogh from within a running akka container i'm able to retrieve `A` records using dig / nslookup

**Comment by eshepelyuk** [comment]
@herzrasen looks like I've found a reason for swarm not working, I have to discuss my discoveries with someoen clever in chat.

**Comment by ktoso** [comment]
> I have to discuss my discoveries with someoen clever in chat.

Please discuss here?

**Comment by eshepelyuk** [comment]
Actually, it's not related to thiis issue, but to general usage of DNS discovery in docker swarm cluster. So I wanted ro move the discussion out of this issue.

**Comment by chbatey** [comment]
Which version of akka-discovery?

**Comment by herzrasen** [comment]
0.17.0. Works with 0.16.0

Christopher Batey <notifications@github.com> schrieb am Mi., 8. Aug. 2018,
12:30:

**Comment by ktoso** [comment]
Good catch... I think this may be because we use the old message type and don't swap it.
Triaged; 

If you'd like to help the solution is to change the messages used for resolving to the new ones: https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/io/dns/DnsProtocol.scala#L49 when we see async-dns configured

**Comment by ktoso** [comment]
I'm digging into this

**Comment by chbatey** [comment]
Does this happen with 0.18.0? 

Note that management uses the new API but other parts of your application / Akka may still use the old API.

**Comment by raboof** [comment]
(the issue mentioned in the comments here was most likely #25454, so fixed in Akka 2.5.15. This seems relatively independent of the warnings that this issue started with, though)

**Comment by raboof** [comment]
This warning seems harmless, disabling it upstream at https://github.com/akka/akka/pull/25744

**Comment by chbatey** [comment]
That's merged now so closing this
