### ISSUE TITLE
DnsSimpleServiceDiscovery is not supporting TCP retry in case of truncated responses.

### ISSUE THREAD

**Issue by pocman** [akka/akka-management#262]
Hi all, 

As mentionned [here](https://github.com/akka/akka-management/pull/214#issuecomment-411447815) and documented [here](https://github.com/ilya-epifanov/akka-dns/issues/16).

I think that akka.io.dns is only using UDP without TCP retry in case of truncated responses. 
This is problematic if the `required-contact-point-nr` is higher than the lookup returned in truncated responses. It's dangerous since the preprod cluster is usually smaller than the production one...

**Comment by chbatey** [comment]
Raised https://github.com/akka/akka/issues/25460 to track this in Akka. Thanks for reporting @pocman
