### ISSUE TITLE
Cross-build to Scala 2.13

### ISSUE THREAD

**Issue by dwijnand** [akka/akka-management#268]
Depends on:
- [x] https://github.com/akka/akka/issues/25105

**Comment by raboof** [comment]
Akka is released for 2.13.0-M3, though, so as a first step we could cross-build to that instead?

**Comment by dwijnand** [comment]
Yep, sounds like a good first step.

**Comment by dwijnand** [comment]
I was going to use this one for 2.13.. but oh well.

**Comment by raboof** [comment]
(sorry, misunderstood then ;) )
