### ISSUE TITLE
Merging slashes for security reasons on URI's will break the REST interface

### ISSUE THREAD

**Issue by avalon12** [akka/akka-management#28]
The REST interface of akka-management expects endpoints to be addressed in the following format:

`PUT /member/akka.tcp://mycluster@example.org:1234`

NGINX' default behaviour is to rewrite double slashes in the path of a URI to single slashes for security reasons (e.g. bypassing URL rewrites and deny, allow rules etc.)

A solution I would like to suggest is to add support for any encoding like base64 or URI encoding in the API to bypass double slash rewriting.

**Comment by patriknw** [comment]
I agree we should support encoding, isn't `:` a also a problem?
As convenience I think we should also support address with only the `hostname:port` part, the prefix can be derived on the server side with `Cluster(system).selfAddress` because that is the same for all nodes in the cluster.

Would you be able to create a pull request @avalon12 ?

**Comment by avalon12** [comment]
Base64 is not safe for urls since it can contain slashes (also multiple slashes after each other in rare cases)
URL encoding is also escaped by NGINX. 
So unless we find another encoding that suitable, we would have to find another way to avoid slashes.

Another option would be to use a pattern like PUT /member/<host>/<port>?cluster=<cluster>

**Comment by patriknw** [comment]
as I tried to say, host and port is the any thing that is needed.
I like `host/port`
I think we can change the URIs to that. Any objections @hveiga ?

**Comment by hveiga** [comment]
I think it makes sense. This sounds like a reasonable solution: `PUT /member/<host>/<port>?cluster=<cluster>`

**Comment by patriknw** [comment]
but `?cluster=<cluster>` is not needed, you still want that as some kind of protection against human errors?

**Comment by hveiga** [comment]
oh yes, you are right. In that case I would vote to remove it since it is not needed.
Then `PUT /member/<host>/<port>` should be sufficient.

**Comment by raboof** [comment]
Should be fixed by #40
