### ISSUE TITLE
Upgrade to akka http 10.1

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#281]
Blocked on play and lagom releasing stable versions that depend on 10.1

See discussion in: https://github.com/akka/akka-management/pull/258

**Comment by dwijnand** [comment]
More concretely stable releases Play 2.7 and Lagom 1.5.

**Comment by patriknw** [comment]
Updated to Akka HTTP 10.1.6 in https://github.com/akka/akka-management/pull/427, also because that is needed for JDK 11
