### ISSUE TITLE
Upgrade to Akka 2.5.15

### ISSUE THREAD

**Issue by johanandren** [akka/akka-management#283]
The async-dns API has changed in a bin-incomp way between 2.5.14 and 2.5.15. So to make akka-management usable with 2.5.15 we must upgrade.

**Comment by eshepelyuk** [comment]
Related to #261

**Comment by patriknw** [comment]
Something in progress in https://github.com/akka/akka-management/pull/275 and then we should release quickly.

**Comment by chbatey** [comment]
:+1:

**Comment by eshepelyuk** [comment]
Since #275 is merged, is there any obstacles stopping from closing the issue and provide a new release ?

**Comment by chbatey** [comment]
@eshepelyuk we'll do a release this week

**Comment by eshepelyuk** [comment]
Thank you very much.

**Comment by dmi3zkm** [comment]
@chbatey Any update on new release ?

**Comment by chbatey** [comment]
0.18.0 syncing to maven central now

**Comment by dmi3zkm** [comment]
> 0.18.0 syncing to maven central now

That's awesome! Many thanks!
