### ISSUE TITLE
Cannot hit public ip of task instance

### ISSUE THREAD

**Issue by toddcooke** [akka/akka-management#293]
When I try to do this:
`watch -n 1 -c "curl http://$TASK_INSTANCE_IP:8558/cluster/members/ | python -mjson.tool"`
after replacing $TASK_INSTANCE_IP with the public ip of one of my task instances, I get:

0curl: (7) Failed to connect to <the public ip> port 8558: Connection refused

**Comment by raboof** [comment]
This seems more like a question than a bug or feature request, so it might be more suitable to bring it up at https://discuss.akka.io. When you bring it up there, it might be useful to explain what orchestration tooling you are using (K8s?). How is your instance exposed on your public IP?
