### ISSUE TITLE
Typed extensions (ClassicActorSystemProvider)

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#298]
Currently users have to:

```
AkkaManagement(system.toUntyped).start()
ClusterBootstrap(system.toUntyped).start()
```

**Comment by 404-** [comment]
I'd like to tackle this. I'm guessing, it would be best to reuse the existing, untyped implementations and do something similar to [AdaptedClusterImpl]. Right?
Also, should there be two separate tickets - one for `AkkaManagement` and another for `ClusterBootstrap`?

[AdaptedClusterImpl]: https://github.com/akka/akka/blob/5514afbe5400811cb60437c9e136878525893697/akka-cluster-typed/src/main/scala/akka/cluster/typed/internal/AdaptedClusterImpl.scala#L138-L139

**Comment by johanandren** [comment]
When 2.5.25 has been released I think this could be achieved using the `akka.actor.ClassicActorSystemProvider` as an apply method parameter.

**Comment by patriknw** [comment]
yes, that would be nice if we can make classic extensions work with typed.ActorSystem parameter. For java we probably have to add `get(ClassicActorSystemProvider)` overload.

**Comment by jrudolph** [comment]
> yes, that would be nice if we can make classic extensions work with typed.ActorSystem parameter. For java we probably have to add `get(ClassicActorSystemProvider)` overload.

Is that something we still want to do (in 2.6)? I didn't find a ticket in akka/akka.

**Comment by patriknw** [comment]
My experiment in https://github.com/akka/akka/pull/27760 didn't work out, and since no other brilliant idea have been proposed we have stayed with the explicit `toClassic` approach.
