### ISSUE TITLE
DNS Discovery broken 

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-management#301]
After upgrading to 0.18.0 I get the following with Akka 2.5.15/16: 

If I disconnect my machine from the internet: 
```
Caused by: com.typesafe.config.ConfigException$WrongType: reference.conf @ jar:file:/Users/heiko/projekte/kunden/moia/streamee/streamee-demo/target/docker/stage/opt/docker/lib/com.typesafe.akka.akka-actor_2.12-2.5.15.jar!/reference.conf: 1052: nameservers has type STRING rather than LIST
```

If the machine is connected, nothing happens for minutes.

**Comment by ktoso** [comment]
Seems a bit weird...

```
  val NameServers: List[InetSocketAddress] = {
    val addrs = Try(c.getString("nameservers")).toOption.toList
      .flatMap {
        case "default" ⇒ getDefaultNameServers(system).getOrElse(failUnableToDetermineDefaultNameservers)
        case address   ⇒ parseNameserverAddress(address) :: Nil
      }
    if (addrs.nonEmpty) addrs
    else c.getStringList("nameservers").asScala.map(parseNameserverAddress)(breakOut)
  }

```

If it is a String first part should work correctly...
If it was NOT a string but was a list the else should trigger and parse correctly as String list...

What's your setting values there?

**Comment by hseeberger** [comment]
I‘m not setting it, the value from reference.conf is used.

To reproduce it use a MBP and disconnect it from the internet.

**Comment by chbatey** [comment]
This is an Akka issue rather than management, I'll move it there

**Comment by chbatey** [comment]
Raied https://github.com/akka/akka/issues/25635 we can keep this open so users discover it.

**Comment by chbatey** [comment]
Fixed via https://github.com/akka/akka/issues/25635 however fixed here is bootstrap won't work as you have no DNS servers configured and the OS returns 0. But it'll give you a nice error message.

**Comment by chbatey** [comment]
No Akka management upgrade needed. Just move to Akka 2.5.17 when it is released (planned this week)
