### ISSUE TITLE
Move management "autostart" from reactive-lib

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#303]
An extension that starts bootstrap and management exists here 
- https://github.com/lightbend/reactive-lib/blob/master/akka-management/src/main/scala/com/lightbend/rp/akkamanagement/AkkaManagementAutostart.scala#L23
- https://github.com/lightbend/reactive-lib/blob/master/akka-cluster-bootstrap/src/main/scala/com/lightbend/rp/akkaclusterbootstrap/ClusterBootstrapAutostart.scala

but should be pulled out and be made part of akka-management if people wanted to enable it; rather than live in reactive-lib.

**Comment by patriknw** [comment]
When is it that you don't want to start it immediately when the extension is loaded? Why do we have the explicit `start()`?

**Comment by ktoso** [comment]
Configuring all the SSL things is usually done in code really, and then you can call that start().
One can argue if that's needed for these endpoints ofc, but we know of some users which dont want anything non-ssl-ed running.

It could be simplified and made into one extension perhaps though, with the TLS thing being explained in more depth if people care for it.

**Comment by chbatey** [comment]
Maybe not do this as part of this sprint but decide if we want it or should it just be documented to call start in projects that are migrating from reactive lib

**Comment by patriknw** [comment]
I think the plan is to move this to a Lagom module. It's currently part of https://github.com/lagom/service-locator-akka-discovery (but I don't know if that is the final destination).

**Comment by TimMoore** [comment]
I think we can close this in favor of lightbend/reactive-lib#111.
