### ISSUE TITLE
akka cluster bootstrap partial formation

### ISSUE THREAD

**Issue by alanngai** [akka/akka-management#306]
I'm using cluster bootstrap with async-dns with a play demo app.  This app uses a cluster singleton to initialize 100 simulated drones which are then distributed in the cluster using cluster sharding.  However, the cluster doesn't always spin up all the drones reliably.   Sometimes it does, but other times, it spins up only 30 drones.  I've collected the logs here

- [node2.log](https://github.com/akka/akka-management/files/2399618/node2.log)
- [node1.log](https://github.com/akka/akka-management/files/2399619/node1.log)

## pre-requisites
- minikube is installed
- running on mac or linux
- es console installed (optional, to look at grafana graphs)

## steps to reproduce
1. clone the [demo app repo](https://github.com/lightbend/es-demos-java)
1. check out tag `git checkout issue-306`
1. cd into the `drone-tracker` directory
1. initialize docker environment with `eval $(minikube docker-env)`
1. build application docker image with `mvn package docker:build`
1. deploy the application with `kubectl apply -f drone-sim.yaml`
1. observe cluster formation via
  - grafana: 
    1. open browser to es-console
    1. click on grafana link
    1. click on dashboards dropdown and select Akka Cluster Sharding
    1. click on time window control in the upper right and select "refresh every 5 sec" then apply
    1. click on "last 5 minutes"
  - log tailing
    1. list pods with `kubectl get pods --namespace=lightbend --selector=app=drone-sim`
    1. tail each pod (in a separate terminal window) with `kubectl logs --namespace=lightbend -f=true <pod name>`

if the pod forms normally, delete the deployment (`kubectl delete -f drone-sim.yaml`) and try again

## expected behavior
**grafana: (10 shards, 100 drones)**
![image](https://user-images.githubusercontent.com/1654394/45795923-14149200-bc53-11e8-9daa-0f9d9794808c.png)

**logs:**
normal logs with no errors

## actual behavior (sometimes)
**grafana: (3 shards, 30 drones)**
![image](https://user-images.githubusercontent.com/1654394/45795996-39a19b80-bc53-11e8-8c7b-ac1a98fb6bb1.png)

**logs:**
- [node2.log](https://github.com/akka/akka-management/files/2399618/node2.log)
- [node1.log](https://github.com/akka/akka-management/files/2399619/node1.log)

**Comment by raboof** [comment]
Thanks for the detailed report! `[error] a.c.s.DDataShardCoordinator - The ShardCoordinator was unable to update a distributed state within 'updating-state-timeout': 10000 millis (retrying), event=ShardHomeAllocated(7,Actor[akka://DroneSim/system/sharding/dronesim.Drone#198817739])` sounds problematic, but I can't quite explain yet why it wouldn't update.

**Comment by chbatey** [comment]
That could happen if Sharding was not started on all of the nodes.

The cluster has formed so this isn't an Akka Management issue so closing this.

Happy to look at some logs, can you ensure they include timestamps and set the level to DEBUG?

**Comment by raboof** [comment]
So it seems it turned out the problem here was that the `ShardRegion` was started from the `ClusterSingleton`, while instead it should be started on each node. That makes sense - missed that - though then the question is why did it sometimes work?

**Comment by patriknw** [comment]
If you start it from a singleton then it will only be started on the active singleton node. The sharding coordinator is also a singleton so that will be active on that node. Requests hitting that node might work.

Yeah, clearly not how it's intended to be used.
