### ISSUE TITLE
Consider 'Removed' as an 'alive' state for K8s liveness checking

### ISSUE THREAD

**Issue by raboof** [akka/akka-management#312]
Since the cluster state is `Removed` while in the process of discovering other nodes (https://github.com/akka/akka/issues/25663), for now I think it would make sense to present ourselves as 'alive' in that state as well, since we don't want Kubernetes to kill us while looking for peers.

**Comment by chbatey** [comment]
:+1: then initial delay isn't required

**Comment by raboof** [comment]
Actually does 'liveness' checking make sense at all? Since it appears when the liveness check fails K8s just kills us - I'm not sure we ever want that?

**Comment by chbatey** [comment]
Only hung apps

**Comment by TimMoore** [comment]
Maybe the liveness check should always respond OK, then, without considering cluster state?

Whatever the result of this discussion is, we should sync up the behavior of `reactive-lib` with the documented recommendation: https://github.com/lightbend/reactive-lib/blob/master/akka-cluster-bootstrap/src/main/scala/com/lightbend/rp/akkaclusterbootstrap/ClusterStatusCheck.scala

**Comment by raboof** [comment]
I agree `Down` should be an 'alive' state as well, will update the PR.
I agree after we implement https://github.com/akka/akka/issues/25663 we may stop considering 'Removed' an 'alive' state.
