### ISSUE TITLE
Akka DNS bootstrap can suffer UDP truncation for long hostnames

### ISSUE THREAD

**Issue by alanngai** [akka/akka-management#313]
I'm unable to reliably form a cluster for my project.  I'm not blocked because I have the k8s-api solution to fall back on.  Just recording this so that we can keep track of it

## relevant info
- hardware: macbook pro i7 6 core processor 32GB RAM
- minikube version v0.28.2
- minikube started with 4 cores and 16GB memory
- [sample project, note the tag](https://github.com/lightbend/es-demos-java/tree/async-dns-fail/drone-tracker)

## prerequisites
- minikube is running
- enterprise suite console installed (optional, but very helpful)
  - import [custom dashboard](https://github.com/lightbend/es-demos-java/blob/async-dns-fail/drone-tracker/grafana.json) by copy and pasting json into grafana
- running mac or linux

## steps to reproduce
- clone and checkout `async-dns-fail`
- set docker env with `eval $(minikube docker-env)`
- from the drone-tracker directory, build with `mvn package docker:build`
- deploy to minikube with `kubectl -f drone-tracker.yaml`
- open up custom grafana dashboard mentioned above and watch the "Node Reachability" graph.  If cluster starts up normally, 5 lines should converge on 5.  If not, all lines are 0

## expected behavior
cluster should form consistently, as verified by "Node Reachability" graph.  Alternatively, you can click on the k8s dashboard and drill down from the deployment to the pods and refresh that page periodically.  If the pods turn all green and stays green, the cluster formed successfully.  If the pods remain red and the restart count increases, the cluster does not form.  You can download the logs from the dashboard directly

## observed behavior
cluster doesn't form consistently.  In this case 2/6 times

![image](https://user-images.githubusercontent.com/1654394/45875911-ed875180-bd4d-11e8-9792-e097bfe69955.png)

here are logs from a previous run where the cluster did not form
- [cluster-form-dns.zip](https://github.com/akka/akka-management/files/2404909/cluster-form-dns.zip)

**Comment by chbatey** [comment]
I'll give this a try

**Comment by raboof** [comment]
The logging suggests the configured 'self' address is `http://172.17.0.14:8558`, making the 'derived' self address something like `172-17-0-14.lightbend.pod.cluster.local`. But the discovery returns names like `3532303937336136.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local` and no addresses, so that doesn't match up.

I suspect we expected an address to be included in the 'additional records' section of the SRV DNS query response, but somehow that wasn't in there or wasn't correlated for some reason.

**Comment by chbatey** [comment]
I was able to reproduce this.

With 5 replicas and k8s very long domain names it hits the UDP limit for DNS.

```
11:14:29 [debug] [akka.tcp://DroneTracker@172.17.0.12:2552/system/IO-DNS/async-dns/$a/$a] - Received message from [/10.96.0.10:53]: [ByteString(0, 1, -121, -128, 0, 1, 0, 4, 0, 0, 0, 0, 11, 95, 109, 97, 110, 97, 103, 101, 109, 101, 110, 116, 4, 95, 116, 99, 112, 35, 100, 114, 111, 110, 101, 45, 116, 114, 97, 99, 107, 101, 114, 45, 99, 108, 117, 115, 116, 101, 114, 45, 98, 111, 111, 116, 115, 116, 114, 97, 112, 45, 100, 110, 115, 9, 108, 105, 103, 104, 116, 98, 101, 110, 100, 3, 115, 118, 99, 7, 99, 108, 117, 115, 116, 101, 114, 5, 108, 111, 99, 97, 108, 0, 0, 33, 0, 1, -64, 12)... and [144] more]
11:14:29 [debug] [akka.tcp://DroneTracker@172.17.0.12:2552/system/IO-DNS/async-dns/$a/$a] - Decoded: Message(1,<AN,QUERY,AA,TR,RD,RA,SUCCESS>,Vector(Question(_management._tcp.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local,RecordType(33,SRV),RecordClass(1,IN))),Vector(SRVRecord(_management._tcp.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local,30,10,20,8558,6438346236623734.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local), SRVRecord(_management._tcp.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local,30,10,20,8558,6230366663396164.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local), SRVRecord(_management._tcp.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local,30,10,20,8558,3237653666313939.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local), SRVRecord(_management._tcp.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local,30,10,20,8558,66646264346164.drone-tracker-cluster-bootstrap-dns.lightbend.svc.cluster.local)),Vector(),Vector())
```

The DNS server doesn't then include the additional records which bootstrap requires to self identify the node.

The important `bit` is the `TR` in the response which says it is truncated.

**Comment by chbatey** [comment]
This will be fixed when https://github.com/akka/akka/issues/25460 is done

**Comment by dwijnand** [comment]
It is done.
