### ISSUE TITLE
Document akka.management.cluster.bootstrap.contact-point-discovery.discovery-method config setting

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-management#316]
Current documentation and examples shows the use of the `akka.discovery.method` config setting to change the service discovery implementation. This is the global default, whereas `akka.management.cluster.bootstrap.contact-point-discovery.discovery-method` is specific to Cluster Bootstrap.

As uses of Akka Service Discovery other than Cluster Bootstrap increase (such as Akka gRPC) it will be confusing to have Cluster Bootstrap examples using `akka.discovery.method`, since usually the preferred Cluster Bootstrap method will be different than the the default for gRPC and other uses.

Documentation and examples for Cluster Bootstrap should be reworked to set `akka.management.cluster.bootstrap.contact-point-discovery.discovery-method` instead.

**Comment by patriknw** [comment]
Somewhat related to https://github.com/akka/akka-management/issues/229

**Comment by alanngai** [comment]
In my case, I wanted to use k8s api for cluster bootstrap and akka-dns for normal service discovery.  I had to use the following settings to make it work

```
akka {
  discovery.method = akka-dns
  io.dns.resolver = async-dns
  management.cluster.bootstrap.contact-point-discovery.discovery-method = akka.discovery.kubernetes-api
}
```
