### ISSUE TITLE
Clarify usage of akka.management.cluster.bootstrap.form-new-cluster in documentation

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-management#351]
It might be misunderstood that `akka.management.cluster.bootstrap.form-new-cluster` will _always_ form a new cluster when `true`, when in fact it will always attempt to join an existing cluster. It's generally safe to set this to `true`, even when scaling out an initial deployment, but safer to set it to `false` once the initial cluster has formed.

Suggestions:

- Clarify in the documentation for this setting that cluster bootstrap always attempts to join an existing cluster, even when set to `true`
- Discuss scenarios where setting it to `false` could prevent accidental formation of multiple clusters when a cluster exists but cannot be discovered (do we know of any?)
- Recommend following the initial deployment with `form-new-cluster=true` with an immediate re-deployment setting `form-new-cluster=false`

**Comment by helena** [comment]
@TimMoore one thought:

```"Recommend following the initial deployment with form-new-cluster=true with an immediate re-deployment setting form-new-cluster=false"```

I question a recommendation requiring a user to deploy then immediately re-deploy, this seems like a possible flaw in our strategy, but regardless, something we should handle for them, and not require a re-deploy.

**Comment by TimMoore** [comment]
It's a fair point… and this isn't strictly required, but I can't think of a way that this could be handled automatically. How would a new node that is starting know whether it's part of an initial deployment or not?

**Comment by chbatey** [comment]
At the moment it is the safest way to deploy a cluster. It is a pain but until we come up with a better solution we should document it.

**Comment by helena** [comment]
@chbatey does this have a milestone to set? I see your recent closed one in this project is 0.20.0

**Comment by chbatey** [comment]
Yep we set the issue, and if there isn't one we set it on the PR so we can find them for release notes. Also can you squash commits in future to keep the history clean?
