### ISSUE TITLE
Document exit on jvm and unsuccessful join seed nodes

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#356]
If contact points are discovered and then shutdown then the joinSeedNodes will never succeed. The Bootstrap coordinator could continue probing in the background and re-call joinSeedNodes if the seeds have changed.

The Scala docs for joinSeedNodes says subsequent calls are ignored but this is only if a cluster has formed.

**Comment by patriknw** [comment]
I suggest using
```
akka.cluster.shutdown-after-unsuccessful-join-seed-nodes = 30s
akka.coordinated-shutdown.exit-jvm = on
```

and then restart the process from scratch.

**Comment by patriknw** [comment]
>  less convenient when in more traditional environments

Why is that? Wouldn't you have a restart loop (checking exit code) also if you launch with a sh script? The process may anyway die for other reasons, such as OOME, and then you want to start it again.

> and bootstrapping via DNS

why is that different?

**Comment by chbatey** [comment]
Good point. We should just document this + that nodes should be wrapped in an auto restart script.

**Comment by chbatey** [comment]
Looks like this made it into #391
