### ISSUE TITLE
Ec2TagBasedSimpleServiceDiscovery blocks on the default dispatcher

### ISSUE THREAD

**Issue by johanandren** [akka/akka-management#377]
The lookup is blocking and is simply done in a `Future { ... }` block (https://github.com/akka/akka-management/blob/master/discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala#L118). This could cause starvation of the default threadpool.

**Comment by sebastianharko** [comment]
@johanandren Assign to me plz, I'll fix it :-)
