### ISSUE TITLE
use scala-java8-compat 0.7.0 when building with Scala 2.11

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#398]
This looks suspicious:

```
      DependencyGroups.AkkaActor ++ Seq(
        "software.amazon.awssdk" % "ecs" % "2.0.0-preview-9",
        "org.scala-lang.modules" %% "scala-java8-compat" % "0.8.0")
```

Why specify `scala-java8-compat` at all? Transitive dependency comes with akka-actor.
If specified it should be 0.7.0 for Scala 2.11, and 0.8.0 for 2.12, as is done in the Akka build.

**Comment by chbatey** [comment]
Why indeed, this is just for one of the aws discovery modules
