### ISSUE TITLE
Extract documentation sample code

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#4]
Extract documentation example code to compiled test source code and use the include extension in Paradox. You find plenty of examples in Alpakka docs: https://github.com/akka/alpakka/tree/master/docs/src/main/paradox

**Comment by chbatey** [comment]
I think we've improved this recently but need to remove the last few instances of code in mark down

**Comment by raboof** [comment]
Just some config and yaml snippets remaining, I think we're doing OK here
