### ISSUE TITLE
EC2 tag based - EC2 client not configurable

### ISSUE THREAD

**Issue by todor-kolev** [akka/akka-management#401]
Running Akka cluster from within a VPC I need to pass in the ProxyHost to the client so it can go out to the EC2 service and get the tags. Unless I've missed it I currently can't see a way of doing this. Probably the best would be to be able to pass in a client instance directly to Akka.

**Comment by sebastianharko** [comment]
@todor-kolev Thanks for creating the issue. A configurable EC2 client is indeed super important. Would the solution proposed in PR #405 work for you ? Cheers!
