### ISSUE TITLE
Update to work with jdk9

### ISSUE THREAD

**Issue by raboof** [akka/akka-management#43]
Tasks:
* [ ] update sbt-header
* [ ] update sbt-scalafmt (perhaps to [neo-sbt-scalafmt](https://github.com/lucidsoftware/neo-sbt-scalafmt))
* [ ] [update sbt-api-mappings](https://github.com/ThoughtWorksInc/sbt-api-mappings/pull/11), which depends on:
  * either: sbt 0.13.17
  * or: [building sbt-best-practice for sbt 1.x](https://github.com/ThoughtWorksInc/sbt-best-practice/issues/3)

**Comment by glammers1** [comment]
Hi, just a comment related to scalafmt:

>  update sbt-scalafmt (perhaps to neo-sbt-scalafmt)

https://github.com/scalameta/scalafmt/issues/1020#issuecomment-384690614

**Comment by raboof** [comment]
This has long since been fixed, i.e. #427
