### ISSUE TITLE
ReadOnly routes not working correctly

### ISSUE THREAD

**Issue by missourian55** [akka/akka-management#432]
I am trying to configure **read only routes**  like below

`akka.management.http.base-path="TestCluster"`
```
            Cluster cluster = Cluster.get(actorSystem);
            ClusterHttpManagementRoutes.readOnly(cluster);
            AkkaManagement.get(cluster.system()).start();
```
After this setup, I am still able to DELETE the member using a rest client (postman)

DELETE http://127.0.0.1:8558/TestCluster/cluster/members/akka.tcp://TestCluster@127.0.0.1:2551

**Comment by chbatey** [comment]
Sounds like a bug, thanks for reporting

**Comment by patriknw** [comment]
I think this is a misunderstanding.
`ClusterHttpManagementRoutes.readOnly(cluster)` is only an accessor (getter) of the read-only routes, which can be included in the application's HTTP server. It's not modifying anything so `AkkaManagement.start` will still run the full set of routes.

Running the read-only routes via `AkkaManagement.start`
https://github.com/akka/akka-management/issues/434

**Comment by chbatey** [comment]
Ah well spotted
