### ISSUE TITLE
Configuration of exposing only read-only routes

### ISSUE THREAD

**Issue by patriknw** [akka/akka-management#434]
Add configuration property to serve only read-only routes for management cluster http. read-only should also be the default so that we don't accidentally expose write operations (e.g. cluster downing) without security considerations. Document that the write operations can be enabled and that security implications of doing so should be considered.

Note that other routes, such as bootstrap and health checks are already read-only.

**Comment by chbatey** [comment]
Should alter the `ManagementRouteProvider` API to distinguish between read and write or just have this inside cluster-http config?

**Comment by patriknw** [comment]
I think it’s overkill to have two separate methods, config and then it’s up to each provider to implement.

**Comment by patriknw** [comment]
Possibly we could add the flag to RouteProviderSettings
