### ISSUE TITLE
K8s-dns: a.m.c.b.LowestAddressJoinDecider - Self contact point [[10.0.32.125:8558]] not found in targets

### ISSUE THREAD

**Issue by sovaalexandr** [akka/akka-management#435]
Hello.
Trying to set-up akka-discovery-dns % 0.20.0 with my akka-cluster app on GKE which uses k8s.
Already SetUp a headless service for DNS discovery and [followed](https://developer.lightbend.com/docs/akka-management/current/bootstrap/index.html) [all](https://developer.lightbend.com/docs/akka-management/current/bootstrap/kubernetes.html) [the](https://developer.lightbend.com/docs/akka-management/current/bootstrap/recipes.html#running-akka-cluster-in-kubernetes) [docs](https://developer.lightbend.com/docs/akka-management/current/discovery/index.html#discovery-method-dns) provided.
When started to apply my pods - cluster just doesn't get together.
I use SRV records and addresses gets resolved
After couple days spent with logs - found out some strange behaviour:
```
2019-01-08 09:06:22.332 [finance-akka.actor.default-dispatcher-4] WARN  a.m.c.b.LowestAddressJoinDecider - Self contact point [[10.0.32.127:8558]] not found in targets
ResolvedTarget(6537333061656333.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None),
ResolvedTarget(3335643565383338.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None),
ResolvedTarget(3461396630633231.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None),
ResolvedTarget(3363326437383765.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None)
```
But **it's there** - the second one! And, as a result:
```
2019-01-08 09:06:22.337 [finance-akka.actor.default-dispatcher-3] INFO  a.m.c.b.LowestAddressJoinDecider - Exceeded stable margins without locating seed-nodes, however this node [10.0.32.127:8558] is NOT the lowest address out of the discovered endpoints in this deployment, thus NOT joining self.
Expecting node [ResolvedTarget(3335643565383338.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None)]
(out of
[
ResolvedTarget(6537333061656333.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None),
ResolvedTarget(3335643565383338.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None),
ResolvedTarget(3461396630633231.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None),
ResolvedTarget(3363326437383765.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local,Some(8558),None)
]) to perform the self-join and initiate the cluster.
```
Further investigate shown that it happens because
```
protected def hostMatches(host: String, target: ResolvedTarget): Boolean =
    host == target.host || target.address.map(_.getHostAddress).contains(host)
```
at [SelfAwareJoinDecider.scala:65](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala#L65) tells that host name is not what I expect.
Further debug with delivery of simple app like this
```
object JvmDebug extends App {
  override def main(args: Array[String]): Unit = {
    val address = InetAddress.getByName(args(0))
    println(s"InetAddress for ${args(0)} is ${address.getHostAddress}. Class is ${address.getClass}")
  }
}

```
into container shown:
```
/opt/docker $ ./bin/jvm-debug 3335643565383338.bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local
InetAddress for 3335643565383338.finance-bootstrap-k8s-dns-internal.mynamespace.svc.cluster.local is 10.0.32.127. Class is class java.net.Inet4Address
```
Then I thought: "Maybe I got this because of misconfiguration, let's see why [canJoinSelf](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala#L42) compares IP with host name?"
It happens that way: akka gets contactPoints by **blocking** [Await.result](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala#L34) from ClusterBootstrap.selfContactPoints And there are two options in specifying a contactPoint:

1.  ClusterBootstrap.settings contain [selfDerivedHost](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala#L101) of form
```
    val selfDerivedHost: Option[String] = for {
      domain <- config.optDefinedValue("akka.discovery.kubernetes-api.pod-domain")
      namespace <- config.optDefinedValue("akka.discovery.kubernetes-api.pod-namespace")
    } yield s"$namespace.pod.$domain"
```
Nevermind config naming, I wasted too much time for this to be purist, but it seems not an option - there is no '.pod.' part in that hostname that I want to specify.
2. host and port being set by `setSelfContactPoint` which gets called from ManagementRouteProviderSettingsImpl on [AkkaManagement.start()](https://github.com/akka/akka-management/blob/3a19c6680d154a9b5750cfd3328f160e78ec8c9f/management/src/main/scala/akka/management/AkkaManagement.scala#L97) which I cannot specify at config because I just don't know it for the time of config - it's [autogenerated](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#srv-records) and _have to_ use [default](https://github.com/akka/akka-management/blob/cace59f771a12327d9396a1e80aad6a52037dfc9/management/src/main/scala/akka/management/AkkaManagementSettings.scala#L22)
```
if (hostname == "<hostname>") InetAddress.getLocalHost.getHostAddress
```

So this is **not** a configuration issue.

The real reason is [ResolvedTarget.apply](https://github.com/akka/akka-management/blob/cace59f771a12327d9396a1e80aad6a52037dfc9/discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala#L49) which uses `InetAddress.getByName` which in turn used at [hostMatches](https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala#L65) will result in string of four octets being comapred to a hostname.
And silent [Try().toOption](https://github.com/akka/akka/blob/bdc90052aac7936b9d2c800c01b0da4d0653c781/akka-discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala#L47) is even bigger trouble.

**Comment by raboof** [comment]
@sovaalexandr Is this no longer an issue? Is there anything we could improve, either in the implementation or in our documentation or error messages?

**Comment by sovaalexandr** [comment]
Still reproduces, but problem is not what described here. Problem at DNS reply parse.

**Comment by raboof** [comment]
Interesting! Let me know if you narrow it down!

**Comment by sovaalexandr** [comment]
@raboof Thank you. There is some improvement that I'd like to contribute. Right now looks like that
```
Index: akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala	(revision c217ef55a41fb5042c799164d9cb519702f04c13)
+++ akka-actor/src/main/scala/akka/io/dns/internal/DnsClient.scala	(date 1546964799000)
@@ -112,7 +112,7 @@
     case Udp.Received(data, remote) ⇒
       log.debug("Received message from [{}]: [{}]", remote, data)
       val msg = Message.parse(data)
-      log.debug("Decoded UDP DNS response [{}]", data)
+      log.debug("Decoded UDP DNS response [{}]", msg)

       if (msg.flags.isTruncated) {
         log.debug("DNS response truncated, falling back to TCP")
```

**Comment by raboof** [comment]
The data is already logged in the `log.debug("Received message from [{}]: [{}]", remote, data)` line before, right?

**Comment by raboof** [comment]
Yes that seems useful - could you provided it as a PR? That way we can properly trace it back to you and make sure you're credited in the release notes.

**Comment by sovaalexandr** [comment]
Sure, if I manage to build akka: Docs and OSGi and check haven't I broke anything.

**Comment by raboof** [comment]
:+1: - let me know if you have any trouble
