### ISSUE TITLE
akka-discovery-dns_2.12 version 0.20.0 is the last, but 1.0.0-RC2 is in the documentation page

### ISSUE THREAD

**Issue by fancywriter** [akka/akka-management#463]
This page is wrong https://developer.lightbend.com/docs/akka-management/current/bootstrap/index.html

It says that **akka-management-cluster-bootstrap** and **akka-discovery-dns** have version "1.0.0-RC2", but for the second one only 0.20.0 is available.

https://search.maven.org/search?q=g:com.lightbend.akka.discovery%20AND%20a:akka-discovery-dns_2.12&core=gav
![screen shot 2019-02-08 at 12 31 30](https://user-images.githubusercontent.com/1200256/52478520-80aa1200-2b9d-11e9-84d6-edfcea019788.png)

**Comment by guizmaii** [comment]
`akka-discovery-dns` should not be used anymore with 1.0.0-RC2. More info, see https://developer.lightbend.com/docs/akka-management/current/migration.html#akka-discovery

**Comment by fancywriter** [comment]
So this doc page still need to be updated.

**Comment by TimMoore** [comment]
Would it be possible for this doc page to include a snippet from one of the integration test projects, rather than hardcoding it in the page?
