### ISSUE TITLE
Inconsistencies in the doc for akka-management port name

### ISSUE THREAD

**Issue by guizmaii** [akka/akka-management#464]
Hi Lightbenders,

How are you since time? Still bending light ? 🙂

While reading entirely the Akka-management doc, I saw some inconsistencies between some parts of the doc.

## 1. Discovery configuration

In `akka-management` doc, to setup the discovery mechanism, it's said to set:

> Set `akka.management.cluster.bootstrap.contact-point-discovery.discovery-method` to `akka.discovery.kubernetes-api`

Here: https://developer.lightbend.com/docs/akka-management/current/bootstrap/kubernetes-api.html

While, in the `akka-discovery-kubernetes-api`, it's said:

> And configure it to be used as default discovery implementation in your application.conf:
>
>```
>akka.discovery {
>  method = kubernetes-api
>}
>```

Here: https://developer.lightbend.com/docs/akka-management/current/discovery/kubernetes.html

Which one says the truth ?

## 2. Akka-management port name

In Akka-management and conf (`reference.conf`), the name by default and advised for the "management" port (`8558`) is: `"management"`.

While in the `akka-discovery-kubernetes-api` doc, the used name is `"akka-mgmt-http"`.
I didn't checked if this key is set or overridden in the  `akka-discovery-kubernetes-api` `reference.conf`.

Again, which one says the truth ?

Thanks 🙂

**Comment by guizmaii** [comment]
Hum maybe there's no inconsistency, the two docs are maybe mutually exclusive ? 🤔

**Comment by TimMoore** [comment]
I think the Kubernetes API method isn't really a good choice as the default service discovery method. It really only makes sense for cluster bootstrap. The docs should be updated.

**Comment by TimMoore** [comment]
@guizmaii to answer your question 2, the port name doesn't really matter, except that what's set in the application configuration needs to match how the port is declared in the Kubernetes `Deployment` resource YAML. Other than that, it's an arbitrary lookup key, so it could be "management", "akka-mgmt-http", "i-like-pie", or anything else you want.

That said, we should stick to a single convention in the documentation, and "management" is preferred over "akka-mgmt-http".

**Comment by TimMoore** [comment]
Also, we should clarify how these values connect using comments in the example configuration.

**Comment by patriknw** [comment]
Renamed "akka-mgmt-http" to "management" in https://github.com/akka/akka-management/pull/477 but note the additional discussion in that PR. Not closing this ticket until we have an agreement.

**Comment by TimMoore** [comment]
I think @jroper is right, and it's better to avoid the need for named ports in the usual case.

Maybe his specific implementation suggestion won't work consistently due to Config's default substitution behavior, but there are other ways to accomplish the same thing. For example, `pod-port-name` could default to `null` and then the code the looks it up could implement the fallback to `akka.management.http.port` when it's not overridden.

**Comment by TimMoore** [comment]
Related: #384

**Comment by TimMoore** [comment]
Two avoid having two separate things in one issue, I'm going to rename this one and split out point 1 to a new issue (since most of the discussion here is about point 2).

**Comment by raboof** [comment]
@TimMoore @jroper based on the discussion here and in #477, I implemented avoiding a named port lookup in #503.

I think determining whether or not to merge this is last remaining decision to make before releasing 1.0.0. Could you have a(nother) look?
