### ISSUE TITLE
Don't document setting kubernetes-api as the default discovery method

### ISSUE THREAD

**Issue by TimMoore** [akka/akka-management#488]
Split from #464 by @guizmaii:

> In `akka-management` doc, to setup the discovery mechanism, it's said to set:
> 
> > Set `akka.management.cluster.bootstrap.contact-point-discovery.discovery-method` to `akka.discovery.kubernetes-api`
> 
> Here: https://developer.lightbend.com/docs/akka-management/current/bootstrap/kubernetes-api.html
> 
> While, in the `akka-discovery-kubernetes-api`, it's said:
> 
> > And configure it to be used as default discovery implementation in your application.conf:
> > ```
> > akka.discovery {
> >  method = kubernetes-api
> > }
> > ```
> 
> Here: https://developer.lightbend.com/docs/akka-management/current/discovery/kubernetes.html
> 
> Which one says the truth ?

These are slightly different: the former sets it as the discovery method for cluster bootstrap only, and the latter sets it as the default method for all service discovery (including cluster bootstrap, if it isn't overridden with the former property).

The Kubernetes API method isn't a good choice as the default service discovery method. It really only makes sense for cluster bootstrap. Service-to-service discovery should generally use `akka-dns`. The docs should be updated to clarify that the Kubernetes API method is really only intended for cluster bootstrap, and only used with the former config property.

**Comment by TimMoore** [comment]
Looks like this is fixed in #468, but perhaps the reasoning could be clarified further in the prose.

**Comment by guizmaii** [comment]
Hey Tim,

Very good idea. I struggled a lot trying to make the `kubernetes-api` based service discovery works. 
I didn't succeed.

Then, I tried the `akka-dns` mechanism and everything worked almost immediately.
