### ISSUE TITLE
Link for akka-management 0.19.0

### ISSUE THREAD

**Issue by suyambuganesh** [akka/akka-management#498]
Hi Team,
The reason I created this issue is that I couldn't find the reference document for akka-management version 0.19.0.

Can you help me with the link?

Thanks

**Comment by raboof** [comment]
Thanks for bringing this up! I expected it at https://developer.lightbend.com/docs/akka-management/0.19.0/, but clearly it is not there. Looking into it.

**Comment by raboof** [comment]
It seems we have our site publishing job configured to keep only the 3 latest tags for akka-management, which are currently 1.0.0-RC1, RC2 and RC3 ;). I'll see if I can widen that.

**Comment by raboof** [comment]
Do you really want 0.19 or is 0.20 sufficient? https://developer.lightbend.com/docs/akka-management/0.20.0/

**Comment by suyambuganesh** [comment]
@raboof 0.20.0 is fine. we have made plans to use latest version in coming weeks. And this link is working. so closing the issue.Thank you.

**Comment by raboof** [comment]
:+1: thanks for the heads-up!
