### ISSUE TITLE
Akka Cluster using discovery method AWS API ECS Discovery - ECS call timeout - akka-discovery-aws-api-async

### ISSUE THREAD

**Issue by asakchris** [akka/akka-management#504]
I am trying to deploy Akka cluster in AWS ECS and using AWS API ECS discovery. [Refer](https://github.com/asakchris/akka-cluster-sample/tree/ecs-discovery) for complete code. I am using akka 2.5.21 and akka management 1.0.0-RC3. Docker image is available [here](https://cloud.docker.com/u/asakchris/repository/docker/asakchris/akka-cluster-sample), refer version 0.1.1.4-SNAPSHOT. I also used cloudformation template to create all AWS resources and it is available in cfn-templates directory, and readme has clear instructions.

While running this ECS cluster, getting below exception, also attached logs [here](https://github.com/akka/akka-management/files/2942238/container-log.txt).
```
2019-03-07 15:15:12,258 DEBUG [sdk-NettyEventLoop-1-0] s.a.a.h.n.n.i.NettyRequestExecutor [ ]: Failed to create connection to https://ecs.us-east-1.amazonaws.com/
io.netty.channel.ConnectTimeoutException: connection timed out: ecs.us-east-1.amazonaws.com/52.46.135.59:443
```
Please help to fix this issue, let me know if you need additional info.

**Comment by davidrogola** [comment]
@asakchris were you able to sort out the issue eventually ?

**Comment by asakchris** [comment]
> @asakchris were you able to sort out the issue eventually ?

Yes. This works if I run container in private subnet that is configured to use a NAT gateway. [Refer](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html) for more details.

**Comment by davidrogola** [comment]
okay thank let me try that out then

**Comment by davidrogola** [comment]
@asakchris for me i am using aws ecs with the ec2 launch type where my task instances are assigned an elastic ip by aws.  Both the ports for akka management and netty.tcp are accessible when I send a curl request inside the ec2 instance that the container instance is running in. I am also able to access the other running task instances ip address from this ec2 instance meaning the task networking is working fine.
But when the akka management bootstrapCoordinator starts looking up the running task instances based on the service name I keep getting the error below:
**[akka.tcp://events-management-service@10.0.1.124:2552/system/bootstrapCoordinator] Resolve attempt failed! Cause: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException** 
Hence cluster formation fails. Could you give me more insights on this ?
