### ISSUE TITLE
Docs v1.0.0 didn't publish

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-management#513]
Despite `v1.0.0` being released, the [published docs](https://developer.lightbend.com/docs/akka-management/current/) still are for version `v1.0.0-RC4`. 

There is no change in the contents but the label is consufing.

**Comment by raboof** [comment]
Hm, https://developer.lightbend.com/docs/akka-management/1.0.0/ is published but indeed somehow 'current' doesn't point to that.

**Comment by chbatey** [comment]
Looks to be fixed now
