### ISSUE TITLE
Kubernetes discovery discovers non-running pods which can break cluster bootstrap

### ISSUE THREAD

**Issue by fredfp** [akka/akka-management#520]
The discovery api discovers pods which are not running and not deleted.

This is problematic (at least) for cluster bootstrap because the IP address of the not running and not deleted pod can be allocated to another running pod.

I had a case where the IP was currently used by a running pod which was in another namespace, and which was member of another akka cluster. The bootstrap algorithm chose to connect to that pod which lead to a failure (because the actor system name and the remoting used were different).

**Comment by chbatey** [comment]
Thanks for reporting. It also is problematic as bootstrap defaults to requiring responses from each of the nodes.
