### ISSUE TITLE
start() does not always return the correct port

### ISSUE THREAD

**Issue by fredfp** [akka/akka-management#525]
It is allowed to set `akka.management.http.port = 0`, I'm assuming this means the same as usual: choose a random port. Binding a random port is very useful for tests as it allows to avoid port conflicts for tests running in parallel.

However when setting `akka.management.http.port = 0`, the uri returned by `start()` does not contain the randomly selected port, but port 80 instead. As such the returned uri cannot be used to connect to the akka management server and is useless.

**Comment by chbatey** [comment]
:+1:
