### ISSUE TITLE
Internal server error when getting shard stats for region that was gracefully shut down

### ISSUE THREAD

**Issue by sebastianharko** [akka/akka-management#53]
I get "Internal server error" when getting shard stats for region that was gracefully shut down.

**Comment by sebastianharko** [comment]
It should show a more graceful error message ;-)

**Comment by patriknw** [comment]
+1, would you be able to create a PR?

**Comment by sebastianharko** [comment]
@patriknw yes , working on it right now

**Comment by sebastianharko** [comment]
@patriknw , created pull request

**Comment by patriknw** [comment]
thanks
