### ISSUE TITLE
Allow kubernetes-api discovery without declaring ports in the pod spec

### ISSUE THREAD

**Issue by jroper** [akka/akka-management#538]
Currently, kubernetes-api discovery only returns results that have the management port configured in the pod spec. This presents a problem for Istio if you want to bypass envoy (see https://github.com/akka/akka-management/issues/209#issuecomment-490764774), and you do want to bypass envoy because you want to use readiness checks and you don't want envoy shutting down to kill your connections to the other nodes in the cluster. The reason it's a problem for Istio is that Istio routes all ports declared in your pod through envoy.

To solve this, it needs to be possible to run kubernetes api discovery in a mode such that it doesn't look at the declared pod ports, it simply returns a list of all pods that match the selector, and assumes that the correct port is the same port that the local machine uses, and so returns that.

**Comment by raboof** [comment]
When discovery returns a host without a port, cluster bootstrap already assumes the management port is the same as locally (https://github.com/akka/akka-management/blob/master/cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala#L286) - so one way to achieve the above might be to convince kubernetes-api discovery not to produce ports. I wonder if that can be achieved by simply not passing in a port name?
