### ISSUE TITLE
can we implement discovery using aws cloud map which is much simpler than ecs awsvpc mode

### ISSUE THREAD

**Issue by aavileli** [akka/akka-management#576]
### Short description

Please describe the feature you'd like to see in short.

We would like to see that Akka cluster seed node discovery is performed using AWS cloud map service which allows ECS and EKS clusters to register tasks or pods. This is a simpler method than using awsvpc network which requires an ENI on every ec2 node.

### Details

Microservices are typically implemented using dynamic resources, such as containers, and can quickly launch and terminate. These resources communicate over API and need to specify the location of their dependent resources from within the application code. However, each of these resources is dynamic with constantly changing locations, making it challenging for individual resources to constantly track and find the locations of all their dependencies. Cloud Map provides a single up-to-date registry of service names and locations, that enables microservices to easily locate one another.

please refer to the following cloud map documentation
https://docs.aws.amazon.com/cloud-map/?id=docs_gateway

**Comment by chbatey** [comment]
Hi @aavileli 

Sorry for the slow reply. We (core Akka team) don't currently maintain the exiting AWS implementations and are left to the community so i don't think we want to add any more AWS options.

That said, Boostrap and Akka Discovery are both pluggable and it is expected that bootstrap mechanisms will be developed and maintained outside of this repository.  So if you still want this I'd suggest building it separately to Akka Management.

We'll be happy to answer any questions for how to do this, you can take any of the existing Akka Discovery implementations as a starting point.

**Comment by Swoorup** [comment]
@aavileli I know this is closed but did you end up finding a solution? We are planning to come up with our own.

**Comment by aavileli** [comment]
@Swoorup we migrated our application to aws eks(kubernetes) and started using **kubernetes-api** in the **akka.discovery** config

`akka.discovery {
  kubernetes-api {
    pod-namespace = ${POD_NAMESPACE}
    # Selector value to query pod API with.
    # `%s` will be replaced with the configured effective name, which defaults to the actor system name
    pod-label-selector = "application=%s"
  }
}`
