### ISSUE TITLE
Dynamically set log levels via HTTP

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#612]
Initially support log level

API should take in a log level and logger to change

Will need to use reflection or provided dependency to avoid putting logback on user classpath

**Comment by ihostage** [comment]
Hi, @chbatey! 👋 
Why don't use an out-of-box [reloadable configuration feature](http://logback.qos.ch/manual/configuration.html#autoScan) of Logback?
It's difficult for many nodes?

**Comment by chbatey** [comment]
Thanks for the link. This is mainly for environments where we don’t have
access to JMX or the file system e.g in Kubernetes

**Comment by ihostage** [comment]
@chbatey 
Our cases:
1. We successfully use this on Kubernates. Logback configuration (with `scan` feature) stored on `ConfigMap` and mount as a volume in pods. One note that after change a ConfigMap needs to delete/create pods because K8S can't hot-change a volume. 😞 
2. We expose JMX port on K8S, but don't use it to change a log level. Thanks for idea 👍

**Comment by chbatey** [comment]
A use case that comes up often is doing it without deleting pods as it is
to debug issues that will go away with a restart

**Comment by ihostage** [comment]
Ohhhh... Sorry, Christopher, my mistake 😞 
I messed up with HOCON configuration, that not reloadable 😄 
Reloadable Logback configuration is all fine. When I change a ConfigMap the file in pods also changed and Logback reloads self-configuration on all pods without a problem.

**Comment by chbatey** [comment]
I think it would be great to document that pattern (not akka specific) and hold off on this until more demand comes then

**Comment by patriknw** [comment]
I think there is already enough demand. I have heard or wanted to recommend this many times. 

Changing the full logback configuration file is a good complement but I guess that changing files in some production deployments are not that easy.

I can probably take a look at implementing this next week.
