### ISSUE TITLE
kubernetes-api discovery does not work with Artery

### ISSUE THREAD

**Issue by olijaun** [akka/akka-management#623]
Hi

I'm using akka-management 1.0.5 and Akka 2.5.23.

It seems that kubernetes-api discovery is prefixing "akka.tcp://" automatically to the URLs. However when using Artery it should be just "akka://". I only managed to use kubernetes-api with netty but not with artery. The "config" discovery works fine and adds the correct prefix according to the remoting used.

The Problem has been mentioned before on stackoverflow: https://stackoverflow.com/questions/58550650/akka-cluster-join-failing-using-kubernetes-api-discovery

Would be great if this could be fixed in order to support Artery which is now the default in Akka 2.6

Thanks and regards
Oliver

**Comment by raboof** [comment]
Thanks for the report, that sounds weird indeed! Our Java example (though it needed an update) seems to still work fine though, and that should use artery... (https://travis-ci.com/akka/akka-sample-cluster-kubernetes-java/builds/138728030)

I wonder what's going on here, would be good to get to the bottom of it!

**Comment by TimMoore** [comment]
The discovery mechanism doesn't provide URLs, only addresses and ports. There most be something else going on. Looking at the StackOverflow post, I'm betting that the problem wasn't really Artery vs. Netty. The Netty configuration posted in the answer sets the hostname, while the Artery configuration doesn't.

**Comment by olijaun** [comment]
I'm setting the hostname but I still have the problem:

```
remote {
    artery {
      transport = tcp
      enabled = on
      canonical {
        hostname = "127.0.0.1"
        hostname = ${?HOSTNAME}
        port = 2550
      }
      bind {
        hostname = "0.0.0.0"
        hostname = ${?HOSTNAME}
        port = 2550
      }
    }
  }
```

`2019-12-05 14:08:45,589 logLev=ERROR class=akka.cluster.ClusterActorRefProvider thread="vmv-vollmacht-service-akka.actor.default-dispatcher-10" corrID= caller= user= No root guardian at [akka.tcp://vmv-vollmacht-service@172.28.119.10:2550]: java.lang.IllegalArgumentException: Wrong protocol of [akka.tcp://vmv-vollmacht-service@172.28.119.10:2550/], expected [akka]`

**Comment by raboof** [comment]
@olijaun could you share (a minified version of) your project so we could have a look? Since our example/test project with kubernetes-api and artery (https://github.com/akka/akka-sample-cluster-kubernetes-java) works fine the problem must be elsewhere, and that might help us narrow down where.

**Comment by olijaun** [comment]
@raboof Thanks for your help. It's quite difficult (and time consuming) to make a minified version. I'll try to get the example application (akka-sample-cluster-kubernetes-java) running in my kubernetes cluster. From there I will play with the config to match more ours. Maybe I can find out where the problem is.

**Comment by raboof** [comment]
> It's quite difficult (and time consuming) to make a minified version.

I can imagine

> I'll try to get the example application (akka-sample-cluster-kubernetes-java) running in my kubernetes cluster. From there I will play with the config to match more ours. Maybe I can find out where the problem is.

Sounds great! Curious...

**Comment by olijaun** [comment]
@raboof Ok, it's quite embarassing... :-) After playing with the akka-sample-cluster-kubernetes-java I figured out that the problem was just because I was switching from netty to artery. kubernetes first replaced one of my two nodes which obviously caused the problem when it tried to contact the node which was still running on netty... I'm sorry to have bothered you and thanks for your help.

**Comment by raboof** [comment]
> Thanks for your help.

No problem! Glad we got to the bottom of it (and good to verify that there's no problem on our side ;) ), thanks for reporting back!
