### ISSUE TITLE
Akka 2.6.0 support for 'akka-discovery-aws-api'

### ISSUE THREAD

**Issue by cosmir17** [akka/akka-management#627]
### Short description
Akka 2.6.0 support for 'akka-discovery-aws-api'

### Details
I am using 'akka-discovery-aws-api' for 'akka distributed data'.
https://mvnrepository.com/artifact/com.lightbend.akka.discovery/akka-discovery-aws-api_2.12

I have the following config:

```
akka {
  loglevel = WARN

  discovery {
    method = aws-api-ec2-tag-based
    aws-api-ec2-tag-based {
      filters = "tag:MyComponent=my-service-name"
    }
  }

  management {
    cluster.bootstrap {
      contact-point-discovery {
        service-name = "my-service-name"
        discovery-method = aws-api-ec2-tag-based
      }
    }
  }

  actor {
    provider = "cluster"

    serializers {
    my serializers....
    }
    serialization-bindings {
      my serializer bindings...
    }

    allow-java-serialization = true
  }
}
```

The application ran and worked fine in test(stage) environment with akka 2.5.25 and I have been using Akka-management 1.0.5 and akka-discovery-aws-api 1.0.5.

I upgraded to Akka 2.6.0. I then got the following error message. So that, I can't run the app.
<img width="1348" alt="Screenshot 2019-12-04 at 14 28 50" src="https://user-images.githubusercontent.com/2845708/70259060-573e2080-1785-11ea-8dbd-447fce08f03f.png">

I was advised to include 'akka-discovery' and I got the following error message:
```
Dec 05 14:35:13 --------- -----[992]: Caused by: com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'akka.remote.artery'.
```
I am using 'akka-discovery-aws-api' because I don't have control over ip addresses of EC2 instances created on AWS.

Can we have native Akka 2.6.0 support for 'akka-discovery-aws-api' so that it would be seamless dev exprience that I have for akka 2.5.25, please? or can you give me an advice to solve the issue I described?

I am using the following dependencies.

the dependencies are:
```
 "com.typesafe.akka"              %% "akka-actor"                           % "2.6.0",
  "com.lightbend.akka.discovery"   %% "akka-discovery-aws-api"               % "1.0.5",
  "com.typesafe.akka"              %% "akka-discovery"                       % "2.6.0",
  "com.lightbend.akka.management"  %% "akka-management-cluster-bootstrap"    % "1.0.5",
  "com.typesafe.akka"              %% "akka-distributed-data"                % "2.6.0",
orgs.akka             %% "akka-actor"              % "2.6.0",
    orgs.akka             %% "akka-slf4j"              % "2.6.0",
    orgs.akka             %% "akka-stream"             % "2.6.0",
    orgs.akka             %% "akka-http"               % "10.1.10",
    orgs.heiko            %% "akka-http-json4s"        % "1.29.1",
```

**Comment by raboof** [comment]
> I was advised to include 'akka-discovery'

Yes - that is what that error message is meant to say, but we have had more reports where this was not clear to users. Perhaps we should further improve the error message, I filed https://github.com/akka/akka/issues/28329 for that.

> com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'akka.remote.artery'.

it looks like it cannot find the `reference.conf` from `akka-remote`. That's strange. One thing that could have gone wrong is the concatenating of all reference.conf resources when packaging your application - some more background on that can be found at https://doc.akka.io/docs/akka/current/additional/packaging.html . How are you packaging/running this app?

**Comment by raboof** [comment]
(to be clear, since the title of this issue is "Akka 2.6.0 support for 'akka-discovery-aws-api'": because we maintain binary compatibility between Akka versions, akka-discovery-aws-api should work fine with both Akka 2.5.x and 2.6.x. If it doesn't then this is a bug - but we haven't had any such report yet)

**Comment by cosmir17** [comment]
@raboof It's my bad. I had the following code in my 'build.sbt'.
```
assemblyMergeStrategy in assembly := {
  case PathList("META-INF", xs @ _*) => MergeStrategy.discard
  case x => MergeStrategy.first
}
```

This was causing the 'reference.conf' issue. My apologies.
Your comment made me realise about the mergeStrategy.

I have removed merge strategy and it's now working fine.

I am closing this 'feature' request.

**Comment by raboof** [comment]
Glad you found it (and that it's OK on our end :smile:)!

**Comment by cosmir17** [comment]
I am glad that I found it 👍
