### ISSUE TITLE
Verify Boostrap on Mesos

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#64]
Supposedly should just work?
Help on checking this would be wonderful @longshorej @fsat

**Comment by bhudgeons** [comment]
I'm trying to get this running in Mesos. 

On the node at 10.0.3.81, the lowest IP node in the cluster, it doesn't recognize that it is, in fact, the node that should self-join. What would cause this?

```
[INFO] [12/08/2017 22:51:35.257] [udn-staging-0-1-4-30eb70-cluster-akka.actor.default-dispatcher-5] [akka.tcp://udn-staging-0-1-4-30eb70-cluster@10.0.3.81:2678/system/headlessServiceDnsBootstrap] Contact point [http://10.0.3.81:12678] exceeded stable margin with no seed-nodes in sight. Considering weather this node is allowed to JOIN itself to initiate a new cluster.
[INFO] [12/08/2017 22:51:40.847] [udn-staging-0-1-4-30eb70-cluster-akka.actor.default-dispatcher-18] [akka.tcp://udn-staging-0-1-4-30eb70-cluster@10.0.3.81:2678/system/headlessServiceDnsBootstrap] Exceeded stable margins without locating seed-nodes, however this node is NOT the lowest address out of the discovered IPs in this deployment, thus NOT joining self. Expecting node Some(ResolvedTarget(10.0.3.81,None)) (out of List(ResolvedTarget(10.0.63.150,None), ResolvedTarget(10.0.3.81,None))) to perform the self-join and initiate the cluster.
```

**Comment by bhudgeons** [comment]
I think that comment is a different issue, not related to Mesos. I'll figure it out and open a different issue if necessary.

**Comment by ygree** [comment]
@ktoso @longshorej I added `dns-demo` and tested in on Mesosphere DC/OS. Here is my PR: https://github.com/akka/akka-management/pull/97

**Comment by longshorej** [comment]
Cool - thanks @ygree. I've got a branch in flight as well adding Marathon API support as an alternative to DNS.

**Comment by ygree** [comment]
@longshorej That would be great to have native Marathon support.

**Comment by longshorej** [comment]
It's here: https://github.com/akka/akka-management/pull/98

**Comment by ygree** [comment]
@longshorej I had the same issue that @bhudgeons mentioned earlier. Basically, when I try to run in bridge mode, bootstrap module cannot recognize self node among seeds:
`Expecting node Some(ResolvedTarget(10.0.3.81,None)) (out of List(ResolvedTarget(10.0.63.150,None), ResolvedTarget(10.0.3.81,None)))`
Because it uses internal interface available only from within container.
Here my fix: https://github.com/akka/akka-management/pull/99

https://github.com/akka/akka-management/pull/99

**Comment by ktoso** [comment]
Solved, thanks @ygree !

**Comment by ygree** [comment]
@ktoso Great! There is also an example of using `discovery-dns` https://github.com/akka/akka-management/pull/97 Can you please merge it for completeness?

**Comment by ktoso** [comment]
Yeah working my way through the PRs
