### ISSUE TITLE
akka-management working with akka 2.6?

### ISSUE THREAD

**Issue by olijaun** [akka/akka-management#662]
Hi

Is the current akka-management version supposed to work with Akka 2.6? Where can I find the compatibility? On https://doc.akka.io/docs/akka-management/current/akka-management.html# it is mentioning scala Versions but not Akka versions. I could not find this information anywhere. I'm sorry if this is a stupid question :-)

Regards
Oliver

**Comment by patriknw** [comment]
It's compatible with Akka 2.6. Sorry that we haven't clarified that in the documentation. You may have to explicitly define more Akka dependencies in your build so that all Akka dependencies are on the same patch version, 2.6.5. Otherwise you will see a runtime exception about that.

**Comment by patriknw** [comment]
Clarified in PR #662

**Comment by olijaun** [comment]
great! thanks a lot!

**Comment by ennru** [comment]
Fixed with #663
