### ISSUE TITLE
Malformed dependency names in docs.

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-management#671]
The dependencies listed in the [docs](https://doc.akka.io/docs/akka-management/current/cluster-http-management.html#dependencies) are not properly expanding `$scala.binary_version$` in all cases:

<img width="892" alt="Screenshot 2020-05-12 at 19 33 06" src="https://user-images.githubusercontent.com/762126/81726408-9a649400-9487-11ea-8c23-2ae1b77b20a0.png">

Related to https://github.com/lightbend/paradox/pull/429

**Comment by ennru** [comment]
Redeployed docs after merging #672
