### ISSUE TITLE
Pull in Kubernetes API based Service Discovery from reactive-lib

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#68]
It's implemented here https://github.com/lightbend/reactive-lib/pull/27/files#diff-2130427a780c9a4e08d28efe21102c61R59 and could be a project here in akka-management, so it'd be plug-and-play.

This can be done once the modularize https://github.com/akka/akka-management/issues/61 issue is done

**Comment by ktoso** [comment]
cc @longshorej

**Comment by longshorej** [comment]
:+1:
