### ISSUE TITLE
Deployment guide: use Java 11 and a JRE

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#681]
When basing the Akka Cluster deployment guide on the Lagom open shift guide we inherited a recommendation of a JDK8 base image. I think we should change this to a JRE11. Opinions?

**Comment by patriknw** [comment]
I think JDK8 could have been back in the times when Cinnamon didn't work with 11.

**Comment by raboof** [comment]
https://developer.lightbend.com/docs/introduction/getting-help/java-versions.html looks pretty Java11-friendly

**Comment by chbatey** [comment]
Okay i'll switch to a 11 JRE and switch out cluster k8s samples
