### ISSUE TITLE
Is it possible to update to akka-http 10.1.12 ? 

### ISSUE THREAD

**Issue by saraiva132** [akka/akka-management#689]
As the question indicates. I would really appreciate if you could bump akka-http version. As long as no conflicts exist. Thank you

**Comment by patriknw** [comment]
You can override that in your own build. Define the Akka HTTP dependencies in your build and they will take preference over the transitive dependencies. Akka HTTP is binary backwards compatible so that should be a safe change.

**Comment by raboof** [comment]
indeed - some more background at https://doc.akka.io/docs/akka/current/project/downstream-upgrade-strategy.html

**Comment by saraiva132** [comment]
Thank you for the swift response. I am indeed overriding but we came across some unusual issues with transitive dependencies. So I was wondering why that was not bumped in the last version `1.0.8`. Thanks for the confirmation that all is good

**Comment by raboof** [comment]
> Thanks for the confirmation that all is good

No problem!

> I am indeed overriding but we came across some unusual issues with transitive dependencies

If you run into any issues with akka-http compatibility then feel free to let us know!
