### ISSUE TITLE
Cluster Formation, Contact Points, and new-cluster-enabled

### ISSUE THREAD

**Issue by longshorej** [akka/akka-management#691]
Hi! I'm thinking about a possible enhancement to the logic in bootstrap. Perhaps when `new-cluster-enabled` is set to `false` for a particular node, it should be excluded from contact points by other nodes and thus not counted towards the `requiredContactPointsNr` count. This could be gated behind a new setting to not change behavior out of the box.

This would allow me to have e.g. one environment responsible for bootstrapping the cluster, and another configured to only join once that environment has bootstrapped it. Both environments would share the same DNS systems and discovery config.

Thoughts? Would you accept a PR? :smile:

**Comment by chbatey** [comment]
How would this work? Taking Kubernetes API as an example, which is based on labels, the configuration option would need to make it to the API server (e.g. as a k8s label/annotation) so it could be used by other nodes to filter.

**Comment by longshorej** [comment]
Couldn't it happen later than that, i.e. include the `new-cluster-enabled` flag in the contact points probe HTTP response, and add an additional "late-stage" filtering step based on this value?

**Comment by longshorej** [comment]
Something like this maybe? https://github.com/akka/akka-management/pull/697

**Comment by chbatey** [comment]
Gotcha. Thinking aloud about how this would work in an environment like Kubernetes.

* Have an initial deployment for creating the initial cluster.
* A second deployment with `new-cluster-enabled` disabled using the same labels so the pods can join the existing cluster via seed node being set by a pod in the initial deployment but this deployment wouldn't be discovered by the first as the pods would be filtered 

Do you imagine the initial deployment being scaled down to 0 after the cluster is formed? Or its required contact points nr being setting to however many replicas there are so we can never have multiple clusters formed by that deployment?

**Comment by longshorej** [comment]
> A second deployment with new-cluster-enabled disabled using the same labels so the pods can join the existing cluster via seed node being set by a pod in the initial deployment but this deployment wouldn't be discovered by the first as the pods would be filtered

I guess we'd have to make sure that nodes with seed nodes (i.e. those part of a cluster already) aren't filtered out - the filtering should only affect cluster formation, not joining.

> Do you imagine the initial deployment being scaled down to 0 after the cluster is formed? Or its required contact points nr being setting to however many replicas there are so we can never have multiple clusters formed by that deployment?

Yeah, set required contact ponts nr to however many replicas there are, and also set the `new-cluster-enabled` flag to false. I think in conjunction with #698 these changes will result in only a single deployment being required without any trade-off in safety. If a node crashes and is rescheduled it will only be able to join an existing cluster.

**Comment by longshorej** [comment]
Hi @chbatey - just thought I'd ping since it's been a few months - is there anything I can provide to further the discussion here?

**Comment by longshorej** [comment]
Ended up going with a custom join decider to turn the cluster formation into a manual process (but retain the dynamic setup that management/bootstrap/discovery provides)
