### ISSUE TITLE
Provide support for SRV records in DNS discovery

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#72]
https://github.com/kubernetes/dns/blob/master/docs/specification.md#232---srv-records

cc @fsat

**Comment by ktoso** [comment]
This will be done in Akka itself, but keeping the ticket here too as it will use it and we shall document it then too

**Comment by TimMoore** [comment]
Raised #215 separately to provide API support for passing the port/protocol name in, which can then be used to construct SRV queries.

**Comment by TimMoore** [comment]
This is happening in https://github.com/akka/akka/pull/25214
