### ISSUE TITLE
Use Akka 2.6 in the scheduled build

### ISSUE THREAD

**Issue by ennru** [akka/akka-management#730]
### Short description

The scheduled build on Travis should use Akka 2.6 to validate compatibility.
As Akka 2.6 defaults to Artery, the tests need to be adapted to pick an available port.

### Details

https://github.com/akka/akka-management/pull/729 disabled Akka 2.6 in the scheduled build

**Comment by chbatey** [comment]
https://github.com/akka/akka-management/pull/742
