### ISSUE TITLE
Failed: Exception in thread "main" java.lang.NoSuchMethodError: akka.http.scaladsl.Http$.apply(Lakka/actor/ClassicActorSystemProvider;)Lakka/http/scaladsl/HttpExt; 	

### ISSUE THREAD

**Issue by chbatey** [akka/akka-management#744]
This is the maven integration test:

https://travis-ci.org/github/akka/akka-management/jobs/716528114

**Comment by chbatey** [comment]
So this appaers to be a problem combining Akka 2.5, with latest Akka Management and Akka HTTP 10.2

**Comment by chbatey** [comment]
This is also fixed by https://github.com/akka/akka-management/pull/742

The issue was we were building with Akka HTTP 10.2 but then the maven test was running with Akka HTTP 10.1

**Comment by chbatey** [comment]
https://github.com/akka/akka-management/pull/742

**Comment by seglo** [comment]
Looks like it's back

https://travis-ci.org/github/akka/akka-management/jobs/721317093#L780

**Comment by ennru** [comment]
This happens when Akka Management is built against Akka HTTP 10.2.0 (in which case it will expect the `Http(ClassicActorSystemProvider)`, but run with Akka HTTP 10.1.11 (from the pom.xml, which just has `Http(ActorSystem)`.

**Comment by patriknw** [comment]
Have we changed the build of management to use http 10.2? Then I think we need to branch and bump minor version for management.

**Comment by ennru** [comment]
No. The scheduled build uses Akka 2.6 and Akka HTTP 10.2, but these tests use Maven and don't change to the versions Akka Management was compiled against.

**Comment by raboof** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/722265365
