### ISSUE TITLE
akka-management-cluster-bootstrap artifact naming

### ISSUE THREAD

**Issue by hseeberger** [akka/akka-management#76]
So the group ID ends with "management". That's fine. But the docs are missing that.

Yet we have to artrifact IDs, one with and one without "management":

```
"com.lightbend.akka.management" %% "akka-management-cluster-bootstrap" % "0.7"
"com.lightbend.akka.management" %% "akka-discovery-dns"                % "0.7"
```

For sake of brevity and DRY, I sugget to remove "management" from bootstrap.

**Comment by ktoso** [comment]
Discovery is wrongly in management btw -- https://github.com/akka/akka-management/pull/75

**Comment by ktoso** [comment]
Made title reflect what the ticket is about.
I don't think it matters that much. Can change since we're in flux with package names anyway.

I need to release a 0.7.1 -- oponions on this rename while I'm at moving things anwyay @johanandren @raboof ?

**Comment by ktoso** [comment]
Fixed discovery to be in `akka`, and management things remain in management, the repetition also remains since `akka-management` is a valid and important module.

State therefore is:

```
$ find . | grep a.jar$
./com/lightbend/akka/akka-discovery-dns_2.12/0.6+9-8ecfc43a/akka-discovery-dns_2.12-0.6+9-8ecfc43a.jar
./com/lightbend/akka/akka-discovery-kubernetes-api_2.12/0.6+9-8ecfc43a/akka-discovery-kubernetes-api_2.12-0.6+9-8ecfc43a.jar
./com/lightbend/akka/akka-discovery_2.12/0.6+9-8ecfc43a/akka-discovery_2.12-0.6+9-8ecfc43a.jar
./com/lightbend/akka/management/akka-management-cluster-bootstrap_2.12/0.6+9-8ecfc43a/akka-management-cluster-bootstrap_2.12-0.6+9-8ecfc43a.jar
./com/lightbend/akka/management/akka-management-cluster-http_2.12/0.6+9-8ecfc43a/akka-management-cluster-http_2.12-0.6+9-8ecfc43a.jar
./com/lightbend/akka/management/akka-management_2.12/0.6+9-8ecfc43a/akka-management_2.12-0.6+9-8ecfc43a.jar
./org/mockito/mockito-core/2.0.35-beta/mockito-core-2.0.35-beta.jar
```

Thanks for chiming in Heiko.

**Comment by ktoso** [comment]
A bit weird, but let's move along with our lives, since Akka artifacts including HTTP are released in the shared groupId anyway.

**Comment by ktoso** [comment]
or `.discovery` in the discovery package...

**Comment by hseeberger** [comment]
Thanks for the changes and the new release.

I don't want to be a pain in the ass, but now we have:

```
"com.lightbend.akka.management" %% "akka-management-cluster-bootstrap" % "0.7.1"
"com.lightbend.akka.discovery"  %% "akka-discovery-dns"                % "0.7.1"
```

Both artefacts are from the GitHub repo akka-management, both come from the same build. This implies to me that they are released togehter, and currently they carry the same version number. That's all fine.

Now I really wonder why they don't have the same group id. Why not have all discovery modules under `com.lightbend.akka.management` which matches the repo and build name?

**Comment by hseeberger** [comment]
To make my last point even clearer, here's a portion of a `build.sbt` file of mine:

``` scala
lazy val library =
  new {
    object Version {
      val akka           = "2.5.8"
      val akkaManagement = "0.7.1"
      // More here
    }
    val akkaClusterBootstrap = "com.lightbend.akka.management" %% "akka-management-cluster-bootstrap" % Version.akkaManagement
    val akkaClusterTools     = "com.typesafe.akka"             %% "akka-cluster-tools"                % Version.akka
    val akkaDiscoveryDns     = "com.lightbend.akka.discovery"  %% "akka-discovery-dns"                % Version.akkaManagement
    // More here
  }
```

If you scroll to the right you'll notice that I use the same value `Version.akkaManagement` for both dependencies `akkaClusterBootstrap` and `akkaDiscoveryDns`, although `akkaDiscoveryDns` has a different group id. This feels odd.

**Comment by ktoso** [comment]
> Both artefacts are from the GitHub repo akka-management, both come from the same build. 

But may not be forever, which is what you're missing from the discussion/context.

**Comment by ktoso** [comment]
This repo is `0.x` and messy quick iteration is to be expected here.
