### ISSUE TITLE
needs update to Akka 2.6.9

### ISSUE THREAD

**Issue by SethTisue** [akka/akka-management#762]
in the Scala community build, I found that with Akka 2.6.9 there are compile errors:

```
[error] /Users/tisue/akka-management/management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala:276:40: overloaded method value apply with alternatives:
[error]   (system: akka.actor.ClassicActorSystemProvider)_$1 <and>
[error]   (system: akka.actor.ActorSystem)_$1
[error]  cannot be applied to ()
[error]             system.registerExtension(p.lookup()) match {
[error]                                        ^
```

reproducible locally with:

```
-  val Akka26Version = "2.6.8"
-  val AkkaVersion = if (CronBuild) Akka26Version else Akka25Version
+  val Akka26Version = "2.6.9"
+  val AkkaVersion = Akka26Version
```

in the community build, I will freeze Akka at 2.6.8 until this is resolved

/cc @patriknw

**Comment by patriknw** [comment]
Thanks for reporting. The reason is that

`def lookup()` was changed to `def lookup` in `ExtensionIdProvider`.
Part of the warning hunt when updating to Scala 2.13.3 https://github.com/akka/akka/pull/28991/files#diff-d69ae7e70eee2ab451f0d757d6fe3506R42

I'll PR the fix to Akka Management.

**Comment by raboof** [comment]
> in the community build, I will freeze Akka at 2.6.8 until this is resolved

@SethTisue this can be unfrozen (assuming you're on HEAD for akka-management?)

**Comment by SethTisue** [comment]
@patriknw https://github.com/scala/community-build/pull/1220 merged 👍
