### ISSUE TITLE
Failed: error in lease-kubernetes-int-test (Kubernetes Lease Integration tests job of travis build)

### ISSUE THREAD

**Issue by seglo** [akka/akka-management#764]
It's not clear from the output what the problem is, but there is a shell script assertion error at the end of the build log.

```
+'[' 3 -eq 10 ']'
```

https://travis-ci.org/github/akka/akka-management/jobs/727345115

**Comment by seglo** [comment]
https://travis-ci.org/github/akka/akka-management/jobs/727678467

**Comment by chbatey** [comment]
Fixed by https://github.com/akka/akka-management/pull/822
