### ISSUE TITLE
Possibly incorrect field in sample kubernetes yaml

### ISSUE THREAD

**Issue by johanandren** [akka/akka-management#772]
https://doc.akka.io/docs/akka-management/current/kubernetes-deployment/preparing-for-production.html#deployment-spec

I get an error that there is no requests field in the limits block when I try to run that on k8.

```
spec.template.spec.containers[0].resources.limits[request]: Invalid value: "request": must be a standard resource type or fully qualified
```

**Comment by patriknw** [comment]
@johanandren isn't this what was fixed in https://github.com/akka/akka-management/pull/765/files
not published to current yet

**Comment by johanandren** [comment]
Ah, indeed. 👍
