### ISSUE TITLE
Implement AWS Discovery via ECS Service

### ISSUE THREAD

**Issue by easel** [akka/akka-management#82]

**Comment by dhpiggott** [comment]
I implemented something this weekend that's working fairly nicely. To start with I implemented it directly in my downstream project.

I'm hoping I'll be able to turn it into a contribution to akka-management in the next week or two.

**Comment by ktoso** [comment]
Sounds promising, please do loop back here, it would be an awesome contribution :)

**Comment by dhpiggott** [comment]
I made a start: https://github.com/akka/akka-management/pull/140
