### ISSUE TITLE
Dealing with service discovery lookup latency

### ISSUE THREAD

**Issue by dope9967** [akka/akka-management#835]
I got an increased latency issue going on in one of the production systems I'm working on. Basically k8s API server latency jumped from 100-200ms to tens of seconds and even though this is k8s provider's responsibility, I was wondering what could be done about it on application's end. If lookups had a configurable cache that would issue requests in the background with configurable timeout, the real k8s control plane issue could be circumvented. I didn't notice anything like this in current implementation. Do you think having such cache would make sense?

Also, it seems that k8s API server latency issue is not tripping any circuit breakers or timeouts. Looking at current implementation, it seems that there are `lookupTimeout` and `resolveTimeout` values defined and used, but they don't appear to be working. Client of these lookups is in my case Lagom's `CircuitBreakingServiceLocator` and circuit breakers for it's calls are wired up after the lookup is done. Is this a bug, missing functionality, anything worth implementing for this?

If these functionalities are found to be beneficial, I'd be willing to work on them.

**Comment by raboof** [comment]
> it seems that there are `lookupTimeout` and `resolveTimeout` values defined and used, but they don't appear to be working. Client of these lookups is in my case Lagom's `CircuitBreakingServiceLocator` and circuit breakers for it's calls are wired up after the lookup is done.

That indeed sounds suspicious, but I guess would require some more digging-in to see if it's a bug or missing functionality.

> If lookups had a configurable cache that would issue requests in the background with configurable timeout, the real k8s control plane issue could be circumvented.

I agree it would be really interesting if updating the lookup could be done outside of the 'critical path' of the actual requests. Of course one classical challenge is when to invalidate this cache: of course it can be updated periodically, but perhaps it should also be invalidated when a connection to the discovered endpoints fails.

It's also not super obvious what the API for this would look like: would consumers of this 'smarter' discovery mechanism still 'poll' the discovery, or should we actively notify listeners when the pool of discovered endpoints changes? Perhaps that is a separate concern, though.

**Comment by dope9967** [comment]
Looking at the tests, I can see that timeouts aren't covered by them. I could try to reproduce the issue in a fork, but my guess is that the cause is these lines:
https://github.com/akka/akka-management/blob/master/discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala#L121-L123
Timeout is set up only for body parsing, not for the actual request, which uses config values with defaults being `idle=60seconds` and `connection=10seconds`. Timeouts like these wouldn't get triggered in a case I described. I'm guessing a simple fix could be to just wrap both the request call and its response parsing with `after(resolveTimeout)`? A fix like this could cause connection pool overflow for Akka HTTP, but at least clients won't hang. Maybe a better fix would be to give lookups a separate connection pool, use `resolveTimeout` for its `idle` and `connection` timeouts?

My first idea for lookup cache was https://doc.akka.io/docs/akka-http/current/common/caching.html, basically a thin wrapper on Caffeine cache. Discovery with caching toggled on would eagerly look up services and put them in the cache based on provided config. Timeouts for cache entries could be pretty low by default - one request per service every second is anyways better than the load k8s API server receives now. Most appropriate lookup intervals and timeouts are of course use case specific so configuration should definitely be exposed to user. Special handling could be done if lookup latency increases, by returning the result of last lookup request and logging a warning that indicates a possibility of stale lookup result - I couldn't come up with anything smarter. Also, the implementation could added somewhere downstream so that every discovery method could benefit from it. What do you think?

**Comment by dope9967** [comment]
@raboof There's also k8s watch API https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes. So there's a way to implement a pretty smart cache, just the implementation has to be k8s discovery specific, for example application config could have a list of services for which discovery would do this watch-based polling and the lookups would go to this cache instead of current implementation.

It would be great if we could come to an agreement on how to proceed with this, I'm quite eager to get started.

**Comment by patriknw** [comment]
What is the usage? HTTP calls? Would a better alternative be to use a Kubernetes Service instead of service discovery?

**Comment by dope9967** [comment]
Yes, I've read the docs for Kubernetes API discovery, there was suggestion for using it only for bootstrap, while using `akka-dns` for everything else, if I've understood it correctly.
So I'm changing this:
```
akka {
  discovery {
    method = aggregate
    aggregate.discovery-methods = ["config", "kubernetes-api", "akka-dns"]
    kubernetes-api.pod-label-selector = "appName=%s"
  }
}
```
To this:
```
akka {
  discovery {
    method = aggregate
    aggregate.discovery-methods = ["config", "akka-dns"]
  }

  management {
    cluster.bootstrap.contact-point-discovery.discovery-method = {
      method = "kubernetes-api"
      kubernetes-api.pod-label-selector = "appName=%s"
    }
  }
}
```
Does this make sense?

**Comment by chbatey** [comment]
Yes using regular k8s services and located either by name or through akka-dns is the right way to go

**Comment by dope9967** [comment]
Great, this setup seems to work fine. I guess there would be some benefits in implementing WATCH based API for looking up services through k8s API, but it isn't supposed to be overloaded in the first place, so I'm closing this issue.
