### ISSUE TITLE
bootstrap-joining-demo folder ?

### ISSUE THREAD

**Issue by sebastianharko** [akka/akka-management#86]
I want to make a demo for the EC2-Tag-Based discovery and possibly have it in the bootstrap-joining-demo folder. However, in the root of the folder right now, there's the kubernetes demo. Can we move the kubernetes demo one folder down in the folder structure so that other demos can be placed ??

I'm thinking of this folder structure:
- bootstrap-joining-demo
  - kubernetes-api
     - would have what's now under bootstrap-joining-demo
  - aws-api
  - other-api
  - etc

**Comment by ktoso** [comment]
that's fine by me, or we simply keep it flat adding -demo to all demos, either works
