### ISSUE TITLE
Don't use AuthenticationProvider for readyness/liveness probes / custom Authentication-Logic

### ISSUE THREAD

**Issue by domdorn** [akka/akka-management#873]
### Short description
Kubernetes/Openshift is unable to access the readyness/liveness probes when an authenticator is specified. 
Please allow a way to either configure an authenticator 
 - only for certain areas (e.g. loglevel, cluster-infos)
 - only for non-readyness/liveness-probes endpoints
 - for custom routes

### Details
I want to be able to require authentication only for certain parts of the management api. E.g. Kubernetes should be able to reach the readyness / liveness-endpoints without authentication, while for endpoints that expose actual information (e.g. cluster membership status, loglevels) or change state (put on loglevels, ...) I'd like to have the Authenticator active. 

The most straightforward way I would imagine this to be, would be, if instead of simply providing the authenticator, I would also get access to the request. Then I could take a look at req.method and req.uri and decide if I want to invoke the authenticator or not. 
So that would mean, to instead/or additionally of providing an `AsyncAuthenticator` in `ManagementRouteProviderSettings`, I would be able to provide an `akka.http.scaladsl.server.directives.AuthenticationDirective` or at least a `(Request, Credentials) => Future[Option[T]]`

That way I could also inspect the request and make my authentication decision based on additional information. This would also allow me to provide custom means of authentication, e.g. ones based on tokens, headers or remote-ip ranges.

**Comment by patriknw** [comment]
Not sure about the details of how to do it but maybe you can grab the routes from https://github.com/akka/akka-management/blob/d3d7d93e5a579e24a5ec1a3c678b1fb3fcf21b83/management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala#L101 and decorate with your own things. Then you are supposed to start the HTTP server yourself.

**Comment by domdorn** [comment]
Thanks! I've now did it like this (in case anyone ever stumbles upon this ticket): 
```
trait ManagementModule {
  def routes: Route
}

object ManagementModule {

  def auth(config: Config): Directives.AsyncAuthenticator[String] = (credentials: Credentials) => {
    credentials match {
      case p @ Credentials.Provided(id) =>
        // potentially
        if (p.verify(config.getString("acme.management.pass")))
          Future.successful(Some(id))
        else
          Future.successful(None)
      case _ => Future.successful(None)
    }
  }

  def decorateRoute(route: Route, config: Config): Route =
    Directives.pathPrefix("mgmt") {
      Directives.concat(
        Directives.get {
          route
        },
        (Directives.post | Directives.put | Directives.delete) {
          Directives.authenticateBasicAsync("mgmt", auth(config)) { user =>
            route
          }
        }
      )
    }

  lazy val live: ZIO[Has[ActorSystem], Nothing, ManagementModule] = for {
    akka <- ZIO.environment[Has[ActorSystem]]
    mgmt <- ZIO.effect(AkkaManagement.get(akka.get)).orDie
  } yield new ManagementModule {
    override def routes: Route = decorateRoute(mgmt.routes, akka.get.settings.config)
  }

}

```
