### ISSUE TITLE
Swipe ssl-config usages from the codebase

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-management#897]
In #893 we removed the usages of `AkkaSslConfig` as that is deprecate in Akka HTTP 10.2.0. There may be some left-overs in form of dependencies or HOCON config snippets still referring to the (now unused) ssl-config. These left-overs should be removed.

**Comment by raboof** [comment]
A quick grep suggests only ./management/src/test/scala/akka/management/AkkaManagementHttpEndpointSpec.scala - did you see other occurances?

**Comment by raboof** [comment]
(removed the case I found, let's take care of any other cases after the release)
