### ISSUE TITLE
Fix the "unknown" in "bootstrap request from unknown"

### ISSUE THREAD

**Issue by ktoso** [akka/akka-management#91]
`13:37:00 INFO  HttpClusterBootstrapRoutes [HttpClusterBootstrapRoutes(akka://lol - Bootstrap request from unknown: Contact Point returning 0 seed-nodes ([Set()])`

I guess the sender has to include the IP, AFAIR we have a setting for it?

**Comment by longshorej** [comment]
This is `akka.http.server.remote-address-header` I think?

**Comment by ktoso** [comment]
Yeah that's it i think, PR please? Heading to bed :)

**Comment by longshorej** [comment]
#92 !
