### ISSUE TITLE
Kubernetes lease name truncation can lead to non-unique lease names

### ISSUE THREAD

**Issue by an-tex** [akka/akka-management#910]
### Versions used 

Versions:
Akka: 2.6.13
Akka Management: 1.0.10

### Expected Behavior

When using a kubernetes lease for cluster sharding (https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#lease), the kubernetes lease names should be unique.

### Actual Behavior

In my case I've enabled a projection using a sharded daemon process, using a kubernetes lease for coordination. The lease names end up being prefixed with `application-shard-sharded-daemon-process-[...]` (42 characters) and being [truncated](https://github.com/akka/akka-management/blob/master/lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesLease.scala#L48) to 63 characters, this leaves only 22 characters for the actual projection name + tag. When truncated, the tag is the first to disappear, this generates the same lease name for different sharding processes. This in turn leads to an error loop with the following logs:

`Lease application-shard-sharded-daemon-process-[...] requested by client application@10.42.2.68:25520 is already owned by client. Previous lease was not released due to ungraceful shutdown.`

`Conflict during heartbeat to lease LeaseResource(Some(application@10.42.2.68:25520),8609152,1622013422731). Lease assumed to be released`

`sharded-daemon-process-[...]: Shard id [2] lease lost, stopping shard and killing [1] entities.`

**Comment by an-tex** [comment]
About possible solutions:
1. When truncating, add a shortish hash suffix based on the full name
2. Use multiple domain segments, as the 63 character limit only counts for each segment. The whole name can be up to 253 characters. Meaning a lease name like `application.shard-sharded-daemon-process.projectionName.tag` would mitigate the limits.

**Comment by octonato** [comment]
The prefix is a concatenation of different bits of information. As described here:

https://doc.akka.io/docs/akka/current/typed/cluster-sharding.html#lease

> To use a lease for sharding set akka.cluster.sharding.use-lease to the configuration location of the lease to use. Each shard will try and acquire a lease with with the name <actor system name>-shard-<type name>-<shard id> and the owner is set to the Cluster(system).selfAddress.hostPort.

Another alternative solution could be to make it configurable. But I think only the `<actor system name>-shard` can be made configurable. The `<type name>-<shard-id>` portion will need to be kept around. 

What about going for solution 2 as suggested by @an-tex, if we failure in case the final name is larger than 253 chars? 

We can also apply solution 1 in case it surpass 253 chars, but the problem I see with hashing is that it will make it harder to follow logs.

**Comment by an-tex** [comment]
@manuelp my "workaround" is NOT to use the kubernetes lease implementation for sharding & singleton :/ it's still fine to use with SBR.

I'd also opt for my 2. solution for the same reasons as @octonato mentioned, with either failure or error log & fallback to default (no lease).

**Comment by manuelp** [comment]
> What about going for solution 2 as suggested by @an-tex, with failure in case the final name is larger than 253 chars?

Early failure would be preferable to silent truncation. At least we'd have an exception that highlights the underlying problem instead of a failing cluster that can't acquire leases.

> We can also apply solution 1 in case it surpass 253 chars, but the problem I see with hashing is that it will make it harder to follow logs.

Certainly it'd be prefereable to have readable names, but in that case a working system with unreadable lease names it'd be still preferable to a failing system with readable ones.

> my "workaround" is NOT to use the kubernetes lease implementation for sharding & singleton :/ it's still fine to use with SBR.

Yes, previously we weren't using the leasing part. But it's useful.

> I'd also opt for my 2. solution for the same reasons as @octonato mentioned, with either failure or error log & fallback to default (no lease).

Readable names and early failures with fallback to no leasing seems to me the best solution so far, if possible.

**Comment by patriknw** [comment]
Fail early sounds good to me. Better to fail hard than error and fallback, because some don't even pay attention to errors.

Changing to `multiple domain segments` sounds good, but it would have to be an opt-in configuration because otherwise we would break rolling updates of existing users.

**Comment by patriknw** [comment]
Fail early check added in https://github.com/akka/akka-management/pull/1194
