### ISSUE TITLE
Feature to never form cluster; only join existing

### ISSUE THREAD

**Issue by longshorej** [akka/akka-management#95]
For some workflows, it would be useful to be able to specify that Akka management should never form a cluster and only join an already formed one. This can sort of be emulated by setting contact points to a very high value, but then the logging isn't very nice.

I'd be happy to PR this if we agree this is useful.

**Comment by ktoso** [comment]
Sounds good, I guess this would be be best to be settable from the application level  as well as config. Please PR :)

**Comment by patriknw** [comment]
I agree, I'd say that this is the "normal case" and the initial bootstrap allowing joining self is a "special case" when looking at it from a production lifecycle perspective (assuming that a system is running for months/years before full restart).
