### ISSUE TITLE
How get cluster status by java api?

### ISSUE THREAD

**Issue by shibd** [akka/akka-management#955]
Hi, everyone.

I know that cluster status can be get through web requests. However, How get cluster status by java api?

**Comment by octonato** [comment]
Hello,  

See this page: https://doc.akka.io/docs/akka/current/additional/operations.html

On the other hand, our [forums](https://discuss.akka.io) would be a better place to ask questions. 

Github issues are for reporting bugs and feature requests, not for general discussion and getting help. Given that, I'm closing this.  

Best.
